In [ ]:
print("hello")
# conda create -p venv python
# conda activate venv

hello


In [1]:
# creating an environment
# conda create -p venv python
# conda activate venv


# venv is a environment name for python we are running

# test.ipynb

# to execute the code type - shift+enter

#pip install ipykernel





In [2]:
for i in range(1,11):
    print("{}*{}={}".format(2,i,2*i))

2*1=2
2*2=4
2*3=6
2*4=8
2*5=10
2*6=12
2*7=14
2*8=16
2*9=18
2*10=20


In [3]:
import numpy as np
a=np.ones((3,4,2),dtype=int)
print(a)
#a= numpy.ones((dimension,rows,columns),dtype=int)

[[[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]]


In [4]:
s1="virat.kohli@blr.com,rohit.sharma@mumbai.com,kl.rahul@lucknow.com"
str1="virat.kohli@blr.com"
f_name=str1[:str1.find(".")]
s_name=str1[str1.find(".")+1:str1.find("@")]
c_name=str1[str1.find("@")+1:str1.find(".",str1.find(".")+1)]
print(f_name)
print(s_name)
print(c_name) 

virat
kohli
blr


In [5]:
s1="virat.kohli@blr.com,rohit.sharma@mumbai.com,kl.rahul@lucknow.com"
s1.split(",")

f_name={}
for str1 in s1.split(","):
    f_name.append(str1[:str1.find(".")])
f_name=[str1[:str1.find(".")] for str1 in s1.split(",")]
s_name=[str1[str1.find(".")+1:str1.find("@")] for str1 in s1.split(",")]
c_name=[str1[str1.find("@")+1:str1.find(".",str1.find(".")+1)] for str1 in s1.split(",")]
print(f_name)
print(s_name)
print(c_name)

AttributeError: 'dict' object has no attribute 'append'

In [ ]:
s1="virat.kohli@blr.com,rohit.sharma@mumbai.com,kl.rahul@lucknow.com"
s1.split(",")

d1={}
f_name=[str1[:str1.find(".")] for str1 in s1.split(",")]
s_name=[str1[str1.find(".")+1:str1.find("@")] for str1 in s1.split(",")]
c_name=[str1[str1.find("@")+1:str1.find(".",str1.find(".")+1)] for str1 in s1.split(",")]
print(f_name)
print(s_name)
print(c_name) 

d1["first_name"]=f_name
d1["second_name"]=s_name
d1["company_name"]=c_name
print(d1)


['virat', 'rohit', 'kl']
['kohli', 'sharma', 'rahul']
['blr', 'mumbai', 'lucknow']
{'first_name': ['virat', 'rohit', 'kl'], 'second_name': ['kohli', 'sharma', 'rahul'], 'company_name': ['blr', 'mumbai', 'lucknow']}


In [ ]:
inplace=True
# mean data will be overwrite

In [ ]:
list1=["hyd","mumbai","chennai","delhi"]

list2=[]
for i in list1:
    list2.append(i.capitalize())

print(list2)

['Hyd', 'Mumbai', 'Chennai', 'Delhi']


In [ ]:
list3=[i.capitalize() for i in list1]
print(list3)


['Hyd', 'Mumbai', 'Chennai', 'Delhi']


In [ ]:
# lambda <arg> :<output>

In [ ]:
#lambda <argument> : <output>,<iterator>
list1=[1,2,3,4,5,6,7,8,9]
for i in map(lambda i:i*i,list1):
    print(i)

1
4
9
16
25
36
49
64
81


In [ ]:
list1=["h#d","mum#bai","banglore","de#hi"]

#print which have #

In [ ]:
list1=["h#d","mum#bai","banglore","de#hi"]

list2=[]
for i in list1:
    if "#" in i:
        list2.append(i)

print(list2)

['h#d', 'mum#bai', 'de#hi']


In [ ]:
[i for i in list1 if "#" in i]

['h#d', 'mum#bai', 'de#hi']

In [ ]:
#lambda <arg>:<condition>,<iterator>

In [ ]:
list(map(lambda i:"#" in i,list1))

[True, True, False, True]

In [ ]:
list(filter(lambda i:"#" in i,list1))

['h#d', 'mum#bai', 'de#hi']

In [ ]:
#n: new line
#t: tab

**List comprehension**

In [ ]:
#syntax:
# [<output> <forloop>]

In [ ]:
list1=["hyd","delhi","bengaluru"]

#list1=["Hyd","Delhi","Bengaluru"]

output=[i.capitalize() for i in list1]
print(output)

['Hyd', 'Delhi', 'Bengaluru']


**List Comprehension with if condtion**


In [ ]:
output=[]
for i in list1:
    if "#" in i:
        output.append(i)

output

#syntax:

# output=[<output> <for_loop> <if_condition>]


[]


In [ ]:
list1=["h#d","de#hi","bengaluru"]
output1=[i for i in list1 if "#" in i]
print(output1)

['h#d', 'de#hi']


In [ ]:
#syntax:-

# [<if_output> <if_condition> else <else_output> <for_loop>]

In [ ]:
list1=[1,2,3,4,5,6]
output=[]

for i in list1:
    if i%2==0:
        output.append("even:{}".format(i))

    else:
        output.append("odd:{}".format(i))

output

['odd:1', 'even:2', 'odd:3', 'even:4', 'odd:5', 'even:6']

In [ ]:
["even:{}".format(i) if i%2==0 else "odd:{}".format(i) for i in list1]

['odd:1', 'even:2', 'odd:3', 'even:4', 'odd:5', 'even:6']

In [ ]:
import string
for i in string.ascii_uppercase:
    print("the ascii value of {} is {}".format(i,ord(i)))

the ascii value of A is 65
the ascii value of B is 66
the ascii value of C is 67
the ascii value of D is 68
the ascii value of E is 69
the ascii value of F is 70
the ascii value of G is 71
the ascii value of H is 72
the ascii value of I is 73
the ascii value of J is 74
the ascii value of K is 75
the ascii value of L is 76
the ascii value of M is 77
the ascii value of N is 78
the ascii value of O is 79
the ascii value of P is 80
the ascii value of Q is 81
the ascii value of R is 82
the ascii value of S is 83
the ascii value of T is 84
the ascii value of U is 85
the ascii value of V is 86
the ascii value of W is 87
the ascii value of X is 88
the ascii value of Y is 89
the ascii value of Z is 90


In [ ]:
import string
for i in string.ascii_lowercase:
    print("the ascii value of {} is {}".format(i,ord(i)))

the ascii value of a is 97
the ascii value of b is 98
the ascii value of c is 99
the ascii value of d is 100
the ascii value of e is 101
the ascii value of f is 102
the ascii value of g is 103
the ascii value of h is 104
the ascii value of i is 105
the ascii value of j is 106
the ascii value of k is 107
the ascii value of l is 108
the ascii value of m is 109
the ascii value of n is 110
the ascii value of o is 111
the ascii value of p is 112
the ascii value of q is 113
the ascii value of r is 114
the ascii value of s is 115
the ascii value of t is 116
the ascii value of u is 117
the ascii value of v is 118
the ascii value of w is 119
the ascii value of x is 120
the ascii value of y is 121
the ascii value of z is 122


In [ ]:
string1="restart"
s1=string1[0]
s2=string1[1:].replace("r","$")
s1+s2

'resta$t'