In [5]:
import numpy as np
import statistics as s

In [6]:
import numpy as np
a=np.arange(25).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [7]:
# to delete complete array
del a

In [8]:
print(a)

NameError: name 'a' is not defined

In [9]:
a=np.arange(5*5).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [14]:
a=np.delete(a,[int(i) for i in range(a.shape[0])],axis=1)
print(a)

IndexError: index 0 is out of bounds for axis 0 with size 0

# universal function
- add()
- subtract()
- multiply()
- divide()
- floor_divide()
- mod()
- power()
- remainder()
- divmod() q=[] r=[]


In [2]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(np.multiply(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.add(arr1, arr2))


[ 6 14 24 36 50]
[-5 -5 -5 -5 -5]
[ 7  9 11 13 15]
