- In numpy we have 2 function to iterate the element of ndarray
1. nditer()
2. ndenumerate()

In [43]:
# nditer()
import numpy as np
a = np.array([10,20,30,40,50,60,70,80,90])
for val in np.nditer(a):
    print(val)

10
20
30
40
50
60
70
80
90


In [44]:
a.shape=(3,3)
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
# displaying 2d
for val in np.nditer(a):
    print(val)

10
20
30
40
50
60
70
80
90


In [45]:
a=np.array([10,20,30,40,50,60,70,80,90,100,110,120])
a.shape=(2,3,2)
print(a)

[[[ 10  20]
  [ 30  40]
  [ 50  60]]

 [[ 70  80]
  [ 90 100]
  [110 120]]]


In [20]:
# diplay 3d
for val in np.nditer(a):
     print(val)

10
20
30
40
50
60
70
80
90
100
110
120


In [46]:
# using ndenumerate
for index,value in np.ndenumerate(a):
    print(index,"-->",value)

(0, 0, 0) --> 10
(0, 0, 1) --> 20
(0, 1, 0) --> 30
(0, 1, 1) --> 40
(0, 2, 0) --> 50
(0, 2, 1) --> 60
(1, 0, 0) --> 70
(1, 0, 1) --> 80
(1, 1, 0) --> 90
(1, 1, 1) --> 100
(1, 2, 0) --> 110
(1, 2, 1) --> 120


In [27]:
# index start with 0 but you want to start it with 1
a = np.array([10,20,30,40,50,60,70,80,90])
for i,v in np.ndenumerate(a):
    print("{}-->{}".format(i[0]+1,v))

1-->10
2-->20
3-->30
4-->40
5-->50
6-->60
7-->70
8-->80
9-->90


In [28]:
# the above is called program define index

In [ ]:
"""  
=> random.rand()
=> random.uniform()- uniform distribution
=> random.randn()
=> random.normal()-normal distribution

_______________________

# data distribution in numpy
- possibility of occurence of value
- value of occurence in list.

_____________________

probability 
"""

In [47]:
# numpy random data distribution
a=np.array([3,5,7,9])
x=np.random.choice(a,p=[0.1,0.3,0.6,0.0],size=(100))
print(x)

[7 7 5 7 5 7 3 7 3 7 7 5 5 7 3 7 3 7 7 7 3 7 7 7 5 5 3 7 7 3 5 7 7 7 7 7 7
 5 7 7 5 7 3 7 7 7 7 7 7 7 7 7 7 5 7 5 7 7 5 7 3 7 5 5 3 7 7 5 5 7 7 7 5 7
 7 5 7 7 7 5 7 5 5 3 7 3 7 5 7 7 7 5 7 5 5 3 7 7 5 5]


In [48]:
print(x.size)

100


In [49]:
import random as r
lst=[10,20,30,40,50,60]
r.shuffle(lst)
print(lst)

[50, 10, 20, 30, 60, 40]


In [50]:
for i in range(len(lst)):
    r.shuffle(lst)
    print(lst)

[60, 10, 50, 40, 20, 30]
[60, 30, 20, 50, 10, 40]
[20, 10, 30, 50, 60, 40]
[60, 40, 50, 10, 30, 20]
[30, 10, 60, 50, 40, 20]
[10, 20, 40, 30, 60, 50]


In [ ]:
s="mississippi"
""" 
shuffle cannot apply on str,byte ,tuple,range,set,frozenset ,dict ,since they are immutable in nature
"""

In [51]:
s="mississippi"
lst=list(s)
for i in range(len(lst)):
    r.shuffle(lst)
    print(''.join(lst))

simpspsisii
ssppsisimii
isippiissms
pssipssiiim
sispssiiipm
siipisispms
smspsiiiips
mpsisispiis
mipisissisp
ipisisssmpi
sssspimiiip


In [ ]:
# example on numpy permutation and combination by numpy.random.shuffle and permutation .


# NumPy random permutation of elements
- a permutation refer to an arrangement of element eg: [3,2,1] is a permuataion of [1,2,3] and vice versa 
- NumPy random module provide two method for this 
1. shuffle() and
2. permutation()

In [52]:
a=np.array([10,20,30,40,50,])
print("original ndarray object=",a)

original ndarray object= [10 20 30 40 50]


In [53]:
# re-arrange the elements of ndarray
np.random.shuffle(a)
print(a)

[20 50 40 30 10]


In [54]:
for i in range(len(a)):
    np.random.shuffle(a)
    print(a)

[10 50 30 20 40]
[20 50 10 30 40]
[10 40 30 20 50]
[10 40 50 20 30]
[30 10 20 40 50]


# generating permutation of array
- the permutation method return a re-arranged array (leaves the original array unchanged)

In [57]:
# by using permutation  for re-arranging elements
arr=np.array([1,2,3,4,5])
print(np.random.permutation(arr))

[5 1 2 3 4]


In [58]:
arr=np.array(list("mississippi"))
x=np.random.permutation(arr)
print(x)

['p' 'i' 's' 'i' 'm' 's' 's' 'i' 's' 'i' 'p']


In [59]:
arr=np.array(list("mississippi"))
for i in range(len(arr)):
    x=np.random.permutation(arr)
    print(x)

['s' 'i' 'i' 's' 's' 'i' 'p' 'p' 's' 'i' 'm']
['s' 's' 'm' 'i' 'i' 'i' 'i' 's' 'p' 's' 'p']
['i' 's' 'p' 'i' 'i' 'p' 'm' 'i' 's' 's' 's']
['i' 's' 'p' 's' 's' 'i' 'p' 'i' 'm' 's' 'i']
['p' 's' 'i' 'p' 's' 'i' 'i' 'm' 's' 'i' 's']
['s' 'i' 's' 's' 'p' 'i' 'i' 'i' 'm' 'p' 's']
['i' 's' 's' 'i' 's' 'm' 'i' 'i' 'p' 's' 'p']
['i' 's' 'i' 's' 's' 'i' 'p' 'm' 's' 'p' 'i']
['i' 'm' 'i' 's' 'i' 'i' 'p' 's' 's' 'p' 's']
['s' 'p' 'i' 's' 'i' 'p' 's' 'i' 's' 'm' 'i']
['p' 'p' 's' 'i' 'i' 's' 's' 'i' 'm' 'i' 's']


In [60]:
print("".join(x))

ppsiissimis


# flatten() and ravel()

In [62]:
a=np.arange(9).reshape(3,3)
print(a)
print("dimension=",a.ndim)
print("shape=",a.shape)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
dimension= 2
shape= (3, 3)


In [65]:
# now make it flatten 
a.shape=(9,)
print(a)

[0 1 2 3 4 5 6 7 8]


In [68]:
a=np.arange(9).reshape(3,3)
print(a.flatten())
print("dimension=",a.ndim)
print("shape=",a.shape)


[0 1 2 3 4 5 6 7 8]
dimension= 2
shape= (3, 3)


In [ ]:
""" 
-->numpy is made from "C" and "FORTRAN"
--> "C"- stand for column measure 
--> "FORTAN" - stand for formula translation 
"""

In [69]:
a=np.arange(9).reshape(3,3)
print("given array")
print(a)
print("-------------------------------")
x=a.flatten("F")
print("content of x=",x)
print("dimension=",x.ndim)
print("shape=",x.shape)



given array
[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------------
content of x= [0 3 6 1 4 7 2 5 8]
dimension= 1
shape= (9,)


In [ ]:
# column become row
# row become column


In [71]:
a=np.arange(9).reshape(3,3)
print("given array")
print(a.ravel())


given array
[0 1 2 3 4 5 6 7 8]
