In [1]:
import numpy as np
arr=np.array([3,6,9])
x=np.lcm.reduce(arr)
print(x)

18


In [2]:
# numpy gcd greatest common denominator
arr=np.array([20,8,32,16])
x=np.gcd.reduce(arr)
print(x)

4


# numpy sorting data

In [4]:
a=np.array([10,2,13,4,-5,0,16,25,-16])
print(a)
# to sort the data 
print(np.sort(a))

[ 10   2  13   4  -5   0  16  25 -16]
[-16  -5   0   2   4  10  13  16  25]


In [5]:
a.shape=(3,3)
print(a)

[[ 10   2  13]
 [  4  -5   0]
 [ 16  25 -16]]


In [6]:
np.sort(a,axis=0)

array([[  4,  -5, -16],
       [ 10,   2,   0],
       [ 16,  25,  13]])

In [ ]:
# here axis=0 represent column , column based sorting


# example of linear algebra
- solve()
- det()
- inv()


In [ ]:
# consider the following linear equation:-
#2x+3y=6 -->1
#6x+4y=3 -->2
# find the value of x and y
a=np.array([[2,3],[6,4]])  
b=np.array([6,3])
sol=np.linalg.solve(a,b)
print(sol)


NameError: name 'np' is not defined

In [12]:
#x+y+z=6
#2x+3y+9z=16
#2x-4y-9z=20
a=np.array([[1,1,1],[2,3,9],[2,-4,-9]])
b=np.array([6,16,20])
sol=np.linalg.solve(a,b)
print(sol)
print("val of x=",sol[0])
print("val of y=",sol[1])
print("val of z=",sol[2])

[ 8.19354839 -3.22580645  1.03225806]
val of x= 8.193548387096774
val of y= -3.225806451612903
val of z= 1.032258064516129


# determinant

In [13]:
# find det of given matrix
a=-np.array([[1,2],[3,4]])
detA=np.linalg.det(a)
print(detA)


-2.0000000000000004


In [16]:
# find det of given matrix
a=-np.array([[1,2,3],[4,5,6],[7,8,2]])
detA=np.linalg.det(a)
print(detA)


-20.99999999999999


In [17]:
# inverse of given matrix
a=np.array([[1,2],[3,4]])
invA=np.linalg.inv(a)
print(invA)

[[-2.   1. ]
 [ 1.5 -0.5]]
