# Finding variance

In [1]:
import numpy as np
a=np.array([[2,4],[1,3]])
print(a,type(a))

[[2 4]
 [1 3]] <class 'numpy.ndarray'>


In [2]:
# calculating mean
print(np.mean(a))

2.5


In [ ]:
# total variance of a
print("variance of a=",np.var(a))

variance of a= 1.25


In [4]:
# column variance of a
print("column variance of a=",np.var(a,axis=0))

column variance of a= [0.25 0.25]


In [5]:
# row variance of a
print("column variance of a=",np.var(a,axis=1))

column variance of a= [1. 1.]


# standard deviation

In [6]:
# standard deviation =math.sqrt(variance)

In [8]:
# total variance
print(np.std(a))

1.118033988749895


In [9]:
# colummn variance
print(np.std(a,axis=0))

[0.5 0.5]


In [10]:
# row variance
print(np.std(a,axis=1))

[1. 1.]


# concept of mode via statistics

In [11]:
import statistics as s
lst=[10,20,30,10,40,50,20,10,15]
print(s.mode(lst))

10


In [ ]:
# mode give most frequent/occurence element

In [16]:
# to find multi frequent element 
lst=[10,20,30,10,40,30,50,20,10,15,20,20,10,15,30,30]
print(s.multimode(lst))

[10, 20, 30]


In [21]:
import numpy as np
a=np.array(list("mississippi"))
print(s.multimode(a))

[np.str_('i'), np.str_('s')]


# ndarray with appending,insert,delete operation

In [23]:
# append()
a=np.array([10,20,30,40])
print(a,type(a))

[10 20 30 40] <class 'numpy.ndarray'>


In [24]:
np.append(a,100)

array([ 10,  20,  30,  40, 100])

In [25]:
# appending multiple values to ndarray object   
a=np.append(a,[50,60,70,80,90,100])
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


In [26]:
# append function with 2d
a=np.array([[10,20],[30,40]])
print(a)

[[10 20]
 [30 40]]


In [29]:
a=np.append(a,[[50,60],[70,80]],axis=0)
print(a)

[[10 20]
 [30 40]
 [50 60]
 [70 80]
 [50 60]
 [70 80]
 [50 60]
 [70 80]]


In [ ]:
a=np.append(a,[[50,60],[70,80]],axis=0)
print(a)

[[1 0]
 [0 1]]


In [33]:
# column
a=np.append(a,[[0,0]],axis=0)
print(a)

[[1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]]


In [35]:
a=np.append(a,[[0],[0],[1],[1],[0]],axis=1)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]]


# insert operation on ndarray

In [36]:
a=np.array([10,20,30,40,50,60])
print(a)

[10 20 30 40 50 60]


In [37]:
print(a,1,15)

[10 20 30 40 50 60] 1 15


In [38]:
a=np.insert(a,1,15)
print(a)

[10 15 20 30 40 50 60]


In [39]:
a=np.insert(a,3,[11,22,33,44])
print(a)

[10 15 20 11 22 33 44 30 40 50 60]


In [40]:
a=np.array([10,20,30,40,50,60,70,80,90])
print(a)

[10 20 30 40 50 60 70 80 90]


In [41]:
a.shape=(3,3)
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [42]:
print(np.insert(a,1,[11,22,33],axis=0))

[[10 20 30]
 [11 22 33]
 [40 50 60]
 [70 80 90]]


In [44]:
print(np.insert(a,1,[44,55,66],axis=1))

[[10 44 20 30]
 [40 55 50 60]
 [70 66 80 90]]


# delete

In [46]:
print(np.delete(a,[0,-2]))

[20 30 40 50 60 70 90]


In [47]:
a=np.arange(5*5).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [48]:
a=np.delete(a,2,axis=0)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [49]:
a=np.arange(5*5).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [50]:
a=np.delete(a,1,axis=1)
print(a)

[[ 0  2  3  4]
 [ 5  7  8  9]
 [10 12 13 14]
 [15 17 18 19]
 [20 22 23 24]]


In [51]:
# axis =1 mean column
# axis =0 mean row