# syntax for 2D slicing:-
- 2DArrayObj[rowbegin:rowend:rowstep,colbegin:colend,colStep[]]

In [1]:
import numpy as np
a=np.arange(16).reshape(4,4)
print(a,type(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>


In [2]:
a[0:4,0:1]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [3]:
a[:,0:1]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [4]:
a[::,:1]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [5]:
# want 4,5,8,9
a[1:3,0:2]

array([[4, 5],
       [8, 9]])

In [6]:
a[1:4,1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [7]:
a[1:3,0:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
a[1:3,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
a[1:3,::]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
# with step value
a[0:4:2,0:4]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [13]:
a[-2:,-2:]

array([[10, 11],
       [14, 15]])

In [ ]:
# its not possible t get principle element by using regular indexing and slicing operations
# you can get diagonal element via advance indexing method.
 

In [14]:
a=np.arange(27).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
"""3D array"""
# [matrixBegin:matrixEnd:matrixStep,rowBegin:rowEnd:rowStep,colBegin:colEnd:colStep]

In [15]:
a[0:2,0:1,0:2]

array([[[ 0,  1]],

       [[ 9, 10]]])

In [16]:
a[:2,:1,:2]

array([[[ 0,  1]],

       [[ 9, 10]]])

In [17]:
a[:,::2,0:1]

array([[[ 0],
        [ 6]],

       [[ 9],
        [15]],

       [[18],
        [24]]])

In [18]:
a[::2,2:3,::2]

array([[[ 6,  8]],

       [[24, 26]]])

In [19]:
# want corner element
a[:,::2,::2]

array([[[ 0,  2],
        [ 6,  8]],

       [[ 9, 11],
        [15, 17]],

       [[18, 20],
        [24, 26]]])

In [21]:
# to convert 3d to 1d
# use ravel and flaten

In [ ]:
"""with slicing operation , we cant get random element 
- for getting random element , we must learn advance indexing and slicing.

"""

# Advance indexing and slicing
- 2D advance indexing:-
identify the row indices of random element
- syntax : rowindices=(row1,row2,row3..row-n)
- identify the column indices of random element
- syntax : columnindices=(col1,col2,col3..col-n)

- pass the row indices and colindices to original

In [23]:
a=np.array([10,20,30,40,50,60,70,80,90])
a.shape=(3,3)
print(a,type(a))

[[10 20 30]
 [40 50 60]
 [70 80 90]] <class 'numpy.ndarray'>


In [ ]:
# to get diagonal element (10,50,90)
rowindices=(0,1,2)# step1
colindices=(0,1,2)#step2
a[rowindices,colindices]

array([10, 50, 90])

In [28]:
#get reverse diagonal element
print(a)
a[(0,1,2),(2,1,0)]

[[10 20 30]
 [40 50 60]
 [70 80 90]]


array([30, 50, 70])

In [30]:
print(a)
a[(0,1,2,2)(1,1,2,0)] # internally process as a[(0,1),(1,1),(2,2),(2,0)]

[[10 20 30]
 [40 50 60]
 [70 80 90]]


<>:2: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
<>:2: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
C:\Users\deepa\AppData\Local\Temp\ipykernel_9852\1474923528.py:2: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
  a[(0,1,2,2)(1,1,2,0)] # internally process as a[(0,1),(1,1),(2,2),(2,0)]


TypeError: 'tuple' object is not callable