In [1]:
import numpy as np
a=np.array([[10,20],[30,40]])
b=np.array([[1,2],[3,4]])
c=np.power(a,b)
print(c)

[[     10     400]
 [  27000 2560000]]


In [3]:
# another method
d=a**b
print(d)

[[     10     400]
 [  27000 2560000]]


In [4]:
e=a/b
print(e)

[[10. 10.]
 [10. 10.]]


In [5]:
a=np.array([[10,20],[30,40]])
b=np.array([[0,1],[2,3]])
c=a/b
print(c)

[[        inf 20.        ]
 [15.         13.33333333]]


C:\Users\deepa\AppData\Local\Temp\ipykernel_8060\1946158853.py:3: RuntimeWarning: divide by zero encountered in divide
  c=a/b


In [7]:
#inf20  mean infinity 
# how to deal with  it 

In [14]:
c[0,0]

np.float64(inf)

In [15]:
c[0,0]="can't divide by zero"

ValueError: could not convert string to float: "can't divide by zero"

In [16]:
d=c.astype(str)
print(d)

[['inf' '20.0']
 ['15.0' '13.333333333333334']]


In [18]:
d[0,0]="can't divide by zero"
print(d)

[["can't divide by zero" '20.0']
 ['15.0' '13.333333333333334']]


In [20]:
e=d.astype(object)
print(e)

[["can't divide by zero" '20.0']
 ['15.0' '13.333333333333334']]


In [21]:
e.dtype

dtype('O')

# where

In [22]:
a=np.array([10,20,30,10,40,10,20,30])
b=np.where(a==10)
print(b)

(array([0, 3, 5]),)


In [27]:
s="mississippi"
a=np.array(list(s))
print(a)

['m' 'i' 's' 's' 'i' 's' 's' 'i' 'p' 'p' 'i']


In [28]:
np.where(a=="s")

(array([2, 3, 5, 6]),)

In [29]:
ind=np.where(np.array(list("abrakadbra"))=="a")
print(ind)

(array([0, 3, 5, 9]),)


In [30]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
ind=np.where(a==4)
print(ind)

(array([1]), array([0]))


In [32]:
ind=np.where(a%3==0)
print(ind)

(array([0, 1, 2]), array([2, 2, 2]))


In [ ]:
# find the element which are not multiple of 3


# NumPy iteration
- 1D
- 2D
- 3D

- nditer()
- ndenumerate()


In [5]:
import numpy as np
a = np.array([10,20,30,40,50,60,70,80])
print(a,type(a),id(a))

[10 20 30 40 50 60 70 80] <class 'numpy.ndarray'> 2834305350896


In [6]:
# display the element of ndarrray using for loop
for val in a:
    print(val)

10
20
30
40
50
60
70
80


In [7]:
# display the element of ndarray by using while loop
i=0
while(i<len(a)):
    print(a[i])
    i=i+1

10
20
30
40
50
60
70
80


In [9]:
a=np.arange(16).reshape(4,4)
print("content of a\n",a)
print("dimension",a.ndim)
print("shape",a.shape)

content of a
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
dimension 2
shape (4, 4)


In [10]:
for i in a:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


In [11]:
for row in a:
    for colelement in row:
        print(colelement)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [12]:
a=np.arange(16).reshape(2,4,2)
print("content of a\n",a)
print("dimension",a.ndim)
print("shape",a.shape)

content of a
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]
dimension 3
shape (2, 4, 2)


In [13]:
for matrix in a:
    for row in matrix:
        for colemement in row:
            print(colemement)
        

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
