# Numpy filtering the data
- 1D,2D,3D or conditional based retrieval from 1D,2D,3D

In [3]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)


[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [6]:
a.shape=(9,)
print(a)

[10 20 30 40 50 60 70 80 90]


In [ ]:

""" 
- procedure-1:-
step1:
create a boolean array
_____________________
step2:-
pass boolean to ndarray
__________

"""

In [8]:
# get the multiple of 3
ba=a%3==0
print(ba,type(ba))

[False False  True False False  True False False  True] <class 'numpy.ndarray'>


In [10]:
# pass the boolean to ndarray object
a[ba]

array([30, 60, 90])

In [11]:
# get the multiple of 4
a[a%4==0]

array([20, 40, 60, 80])

In [12]:
a=np.array([[10,-20,-30],[40,-50,60],[70,-80,-90]])
print(a,type(a))

[[ 10 -20 -30]
 [ 40 -50  60]
 [ 70 -80 -90]] <class 'numpy.ndarray'>


In [14]:
#get all positive value
pa=a[a>0]
print(pa,type(pa))

[10 40 60 70] <class 'numpy.ndarray'>


In [15]:
#get all the negative value
na=a[a<0]
print(na,type(na))

[-20 -30 -50 -80 -90] <class 'numpy.ndarray'>


# numpy copy vs view
- copy()
- view()

In [18]:
a=np.array([10,20,30,40])
print(a,type(a))

[10 20 30 40] <class 'numpy.ndarray'>


In [21]:
b=a.copy()
print("original array = {} and {}".format(a,type(a)))
print("copied array = {} and {}".format(b,type(b)))


original array = [10 20 30 40] and <class 'numpy.ndarray'>
copied array = [10 20 30 40] and <class 'numpy.ndarray'>


In [22]:
a[0]=100
print("original array = {} and {}".format(a,type(a)))
print("copied array = {} and {}".format(b,type(b)))

original array = [100  20  30  40] and <class 'numpy.ndarray'>
copied array = [10 20 30 40] and <class 'numpy.ndarray'>


# view()

In [24]:
b=a.view()
print("original array = {} and {}".format(a,type(a)))
print("copied array = {} and {}".format(b,type(b)))

original array = [100  20  30  40] and <class 'numpy.ndarray'>
copied array = [100  20  30  40] and <class 'numpy.ndarray'>


In [25]:
# it is just deep copy changes on one will affect the others

In [ ]:
# arithmetic operation on ndarray
#or
#arithmetic operation
"""   
+
-
*
/
//
%
**

 """

In [2]:
import numpy as np
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, device=None, like=None)
    Return a new array of given shape and type, filled with ones.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    device : str, optional
        The device on which to place the created array. Default: None.
        For Array-API interoperability only, so must be ``"cpu"`` if passed.

        .. versionadded:: 2.0.0
    like : array_like, optional
            Reference object to allow the creation of arrays which are not
            NumPy arrays. If an array-like passed in as ``like`` supports
  

In [8]:
a=np.arange(32).reshape(8,8)
print(a)

ValueError: cannot reshape array of size 32 into shape (8,8)