In [ ]:
# example of numpy swaping 

In [1]:
import numpy as np
# create array with shape(4,3)
my_array=np.arange(12).reshape(4,3)
print("original array:")
print(my_array)
# swaping the column with index of original array
my_array[:,[2,0]]=my_array[:,[0,2]]
print("after swaping the array the last column and first column :")
print(my_array)

original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
after swaping the array the last column and first column :
[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


In [4]:
# function defination for swap

""" 
import numpy as np
# creating array
def swap(arr,startIndex,lastIndex):
     arr[:,[startIndex,lastIndex]]=arr[lastIndex,startIndex]
   
"""

' \nimport numpy as np\n# creating array\ndef swap(arr,startIndex,lastIndex):\n     arr[:,[startIndex,lastIndex]]=arr[lastIndex,startIndex]\n   \n'

# Numpy statistics operation:-
1. amax()
2. amin()
3. mean()
4. median()
5. mode() not present in python module
6. var() # variance 
7. std() # standard deviation

In [5]:
# 1d array
a=np.array([10,20,3,5,14,-6,26])
print(np.amax(a))
print(np.amin(a))


26
-6


In [9]:
# 2d array related row max and col max
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(np.amax(a))
print(np.amin(a))
print(np.amax(a,axis=0))
print(np.amax(a,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
1
[7 8 9]
[3 6 9]


In [14]:
# find the mean 
lst=[10,20,30,40,50,60,70,80,90,100]
s=0
for val in lst:
    s=s+val
    
print(":sum=",s)
print("mean or average=",(s/len(lst)))
print("using pre define function:",(sum(lst)/len(lst)))

:sum= 550
mean or average= 55.0
using pre define function: 55.0


In [15]:
# finding mean of 1D array
a=np.array([10,20,30,40,50,60,70,80,90,100])
print("content of a",a)
print("mean of 1D array",np.mean(a))


content of a [ 10  20  30  40  50  60  70  80  90 100]
mean of 1D array 55.0


In [19]:
# finding mean of 2D array

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)
print("mean of 2D array",np.mean(a))
print("mean of 2D array along axis 0",np.mean(a,axis=0))
print("mean of 2D array along axis 1",np.mean(a,axis=1))

[[10 20 30]
 [40 50 60]
 [70 80 90]]
mean of 2D array 50.0
mean of 2D array along axis 0 [40. 50. 60.]
mean of 2D array along axis 1 [20. 50. 80.]


In [21]:
""" 
0 axis mean = y axis or vertical axis or column
1 axis mean = x axis or horizontal axis or row

"""

' \n0 axis mean = y axis or vertical axis or column\n1 axis mean = x axis or horizontal axis or row\n\n'

In [26]:
# finding median of 1D array
sals=[12,35,24,6,36,8,9]
asals=np.array(sals)
print("list of average salary",asals)
mdsal=np.median(asals)
print(mdsal)
print("mean sal",np.mean(asals))

list of average salary [12 35 24  6 36  8  9]
12.0
mean sal 18.571428571428573


In [ ]:
# find the median of 2-d array with number of values
import numpy as np
a=np.array([[10,2,20],[5,15,8],[5,15,4]])
print(a)
print("median",np.median(a))
print("median of 2d array",np.mean(a))



[[10  2 20]
 [ 5 15  8]
 [ 5 15  4]]
median 8.0
median of 2d array 9.333333333333334


In [6]:
print(np.mode)

AttributeError: module 'numpy' has no attribute 'mode'

In [ ]:
# we dont have mode in numpy