# 1. array()
- syntax:-
- varname=numpy.array(object.dtype)
- this function is used  for converting traditional python objects into ndarray object



- Numpy stand for numerical python 
- to deal with arrays based computing + complex operation
- travis oliphan developed numpy 
- he developed numpy in C, Python language
"""

In [3]:
import numpy as np
b=90
a=np.array(b)
print(a,type(a))

90 <class 'numpy.ndarray'>


In [4]:
print(a.ndim)

0


In [5]:
print(a.shape)

()


In [6]:
print(a.size)

1


In [7]:
print(a.dtype)

int64


In [9]:
b=3.4
a=np.array(b)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

3.4 <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type float64


In [10]:
b=3.4+4.5j
a=np.array(b)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

(3.4+4.5j) <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type complex128


In [11]:
b="python"
a=np.array(b)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

python <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type <U6


In [12]:
r=range(7)
print(r,type(r))

range(0, 7) <class 'range'>


In [13]:
for val in range(10,21):
    print(val,end="\t")

10	11	12	13	14	15	16	17	18	19	20	

In [14]:
r=range(10,51,2)
a=np.array(r)
print(a,end="\t")

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]	

In [15]:
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50] <class 'numpy.ndarray'>
dimension 1
shape (21,)
size 21
internal data type int64


In [16]:
a=np.array(range(6),dtype=bool)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[False  True  True  True  True  True] <class 'numpy.ndarray'>
dimension 1
shape (6,)
size 6
internal data type bool


In [17]:
a=np.array(range(6),dtype=int)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[0 1 2 3 4 5] <class 'numpy.ndarray'>
dimension 1
shape (6,)
size 6
internal data type int64


# now i want to reshape the 1D to 2D array:-

- syntax: for shape attribute
- ndarrayobj.shape=(rows,cols)
-  syntax: for reshape attribute
- ndarrayobj=ndarrayobj.reshape(rows,cols)

In [18]:
a=np.array(range(100,156,5))
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
dimension 1
shape (12,)
size 12
internal data type int64


In [19]:
a.shape=(4,3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[100 105 110]
 [115 120 125]
 [130 135 140]
 [145 150 155]] <class 'numpy.ndarray'>
dimension 2
shape (4, 3)
size 12
internal data type int64


In [21]:
a.shape=(12,)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
dimension 1
shape (12,)
size 12
internal data type int64


In [22]:
print(a)

[100 105 110 115 120 125 130 135 140 145 150 155]


In [24]:
a.reshape(4,3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
dimension 1
shape (12,)
size 12
internal data type int64


In [26]:
a=a.reshape(12,)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
dimension 1
shape (12,)
size 12
internal data type int64


In [28]:
a=np.array(range(0,16))
a.shape=(2,2,2,2)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]] <class 'numpy.ndarray'>
dimension 4
shape (2, 2, 2, 2)
size 16
internal data type int64


In [36]:
lst=[10,20,30,40,50,60,70,80,90,100,110,120,130,140,160]
a.shape=(4,4)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>
dimension 2
shape (4, 4)
size 16
internal data type int64


In [39]:
a.shape=(2,2,4)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] <class 'numpy.ndarray'>
dimension 3
shape (2, 2, 4)
size 16
internal data type int64


In [40]:
# to flatten
a.shape=(16,)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] <class 'numpy.ndarray'>
dimension 1
shape (16,)
size 16
internal data type int64


In [41]:
s1={10,20,30,40,50,60}
print(s1,type(s1))

{50, 20, 40, 10, 60, 30} <class 'set'>


In [42]:
a=np.array(s1)

print(a,type(a))

{50, 20, 40, 10, 60, 30} <class 'numpy.ndarray'>


In [43]:
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

{50, 20, 40, 10, 60, 30} <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type object


- set never maintain indexing.
hence matrix formation with set and frozenset is not possible.


In [47]:
d1={10:"python",20:"java",30:"c",40:"c++"}

a=np.array(d1)
print(a,type(a))
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

{10: 'python', 20: 'java', 30: 'c', 40: 'c++'} <class 'numpy.ndarray'>
{10: 'python', 20: 'java', 30: 'c', 40: 'c++'} <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type object
