# 2. arange()
- arange() is used for generating range of values with equal interval of value(default interval value or step value is 1)
- syntax:-
- varname=numpy.arange(start)
- varname=numpy.arange(start,end)
- varname=numpy.arange(start,end,step)

- arange() by default create an object of ndarray with 1D  array only ,it cannot built 2D and n-dimension array

- to built 2D and n-D array from arange() function we use reshape() or shape attribute.
 

In [2]:
import numpy as np
a=np.arange(10)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
dimension 1
shape (10,)
size 10
internal data type int64


In [6]:
a.shape=(5,2)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] <class 'numpy.ndarray'>
dimension 2
shape (5, 2)
size 10
internal data type int64


In [8]:
a=np.arange(10,22)
print(a,type(a),len(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[10 11 12 13 14 15 16 17 18 19 20 21] <class 'numpy.ndarray'> 12
dimension 1
shape (12,)
size 12
internal data type int64


In [9]:
a.shape=(2,2,3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]] <class 'numpy.ndarray'>
dimension 3
shape (2, 2, 3)
size 12
internal data type int64


In [10]:
a=np.arange(10,22).reshape(2,3,2)
print(a,type(a))

[[[10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]]] <class 'numpy.ndarray'>


In [12]:
a=np.arange(10,106,5).reshape(5,4)
print(a,type(a),len(a))

[[ 10  15  20  25]
 [ 30  35  40  45]
 [ 50  55  60  65]
 [ 70  75  80  85]
 [ 90  95 100 105]] <class 'numpy.ndarray'> 5


# linspace()
- syntax:-
- varname=numpy.linspace(start,stop,num,endpoint,restep,dtype)
- 

In [13]:
a=np.linspace(1,2)

print(a,type(a))

[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ] <class 'numpy.ndarray'>


In [14]:
a=np.linspace(1,2,num=5)
print(a,type(a))

[1.   1.25 1.5  1.75 2.  ] <class 'numpy.ndarray'>


In [16]:
a=np.linspace(1,2,num=5,endpoint=False)
print(a,type(a))

[1.  1.2 1.4 1.6 1.8] <class 'numpy.ndarray'>


In [17]:
a=np.linspace(1,2,num=5,retstep=True)
print(a,type(a))

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), np.float64(0.25)) <class 'tuple'>


# zeros()
- syntax:-
- varname=numpy.zeros(shape,dtype)

In [20]:
l1=[0,0,0,0]
a=np.array(l1)
print(a,type(a))
a.shape=(2,2)
print(a,type(a))

[0 0 0 0] <class 'numpy.ndarray'>
[[0 0]
 [0 0]] <class 'numpy.ndarray'>


In [23]:
a=np.zeros((2,2),dtype=int)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[[0 0]
 [0 0]] <class 'numpy.ndarray'>
dimension 2
shape (2, 2)
size 4
internal data type int64


In [24]:
a=np.zeros((3,3,3),dtype=int)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]] <class 'numpy.ndarray'>
dimension 3
shape (3, 3, 3)
size 27
internal data type int64


# ones()
- syntax:-
- 

In [25]:
a=np.ones(3,dtype=int)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[1 1 1] <class 'numpy.ndarray'>
dimension 1
shape (3,)
size 3
internal data type int64


In [26]:
a=np.ones((2,3,4),dtype=int)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] <class 'numpy.ndarray'>
dimension 3
shape (2, 3, 4)
size 24
internal data type int64


# full()
- syntax:-
- varname=numpy.full(shape,fill_value,dtype)


In [27]:
a=np.full(6,9)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[9 9 9 9 9 9] <class 'numpy.ndarray'>
dimension 1
shape (6,)
size 6
internal data type int64


In [28]:
a=np.full(6,9).reshape(2,3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[[9 9 9]
 [9 9 9]] <class 'numpy.ndarray'>
dimension 2
shape (2, 3)
size 6
internal data type int64


In [29]:
a=np.full((3,3),6)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[[6 6 6]
 [6 6 6]
 [6 6 6]] <class 'numpy.ndarray'>
dimension 2
shape (3, 3)
size 9
internal data type int64


In [30]:
a=np.full((3,3,3),6)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[[6 6 6]
  [6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]]] <class 'numpy.ndarray'>
dimension 3
shape (3, 3, 3)
size 27
internal data type int64


In [31]:
a=np.full((3,3,3),"itty")
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']]

 [['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']]

 [['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']]] <class 'numpy.ndarray'>
dimension 3
shape (3, 3, 3)
size 27
internal data type <U4


# identity()
- syntax:-
- varname=numpy.identity(N,dtype)

In [35]:
a=np.identity(3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <class 'numpy.ndarray'>
dimension 2
shape (3, 3)
size 9
internal data type float64


# eye()

- varname= numpy.eye(N,M=none,k=0,dtype)

In [4]:
a= np.identity(5,dtype=int)
print(a,type(a))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] <class 'numpy.ndarray'>


In [5]:
a= np.eye(5,dtype=int)
print(a,type(a))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] <class 'numpy.ndarray'>


In [7]:
a= np.eye(5,k=-1,dtype=int)
print(a,type(a))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]] <class 'numpy.ndarray'>


In [8]:
a= np.eye(5,k=-2,dtype=int)
print(a,type(a))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]] <class 'numpy.ndarray'>


In [9]:
a= np.eye(3,5,dtype=int)
print(a,type(a))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]] <class 'numpy.ndarray'>


In [10]:
a= np.eye(5,3,dtype=int)
print(a,type(a))

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]] <class 'numpy.ndarray'>
