# Random number generation in numpy:-
- numpy.random
- 1. randint()
- 2. rand()
- 3. uniform()
- 4. randn()
- 5. normal()
- 6. shuffle()


- --> these are very much useful data science algorithm.(random number generation in numpy:-)

In [ ]:
import numpy as np
""" 
_____________________________________  
 1. randint() :- 
 syntax:-
 randint(low, high=None, size=None, dtype=int)
_____________________________________
- 2. rand()
_____________________________________
- 3. uniform()
_____________________________________
- 4. randn()
_____________________________________
- 5. normal()
_____________________________________
- 6. shuffle()
_____________________________________



"""


In [3]:
a=np.random.randint(10)
print(a,type(a))

3 <class 'int'>


In [4]:
a=np.random.randint(10,30,size=(10,20))
print(a,type(a))

[[27 12 14 29 27 24 20 10 27 21 21 18 19 21 17 23 21 19 11 14]
 [18 28 13 26 21 21 29 13 11 14 29 26 26 15 18 15 18 15 18 16]
 [23 16 28 13 12 27 21 26 27 22 20 15 24 17 26 24 13 23 29 19]
 [10 10 14 23 15 29 13 14 26 29 26 11 12 14 15 26 22 20 13 21]
 [26 15 28 26 12 25 14 14 17 19 25 12 27 21 29 16 14 13 16 10]
 [17 19 24 21 22 23 11 17 27 21 24 20 14 26 20 27 10 29 25 10]
 [29 17 24 19 25 13 29 18 10 23 29 24 23 22 12 11 26 16 20 26]
 [12 20 23 12 25 12 12 15 21 14 26 11 14 13 16 27 11 21 19 17]
 [23 26 20 15 12 16 11 27 20 25 18 14 12 19 16 12 15 20 28 21]
 [22 24 24 22 21 17 16 18 22 14 10 19 23 13 19 22 17 28 19 15]] <class 'numpy.ndarray'>


In [5]:
a=np.random.randint(10,30,size=(3,3,3))
print(a,type(a))

[[[24 25 24]
  [24 26 16]
  [18 24 14]]

 [[18 13 18]
  [25 19 22]
  [16 11 17]]

 [[12 25 15]
  [22 22 27]
  [22 27 18]]] <class 'numpy.ndarray'>


In [6]:
a=np.random.randint(10,30,size=(2,2,2,2))
print(a,type(a))

[[[[18 11]
   [16 17]]

  [[16 13]
   [16 25]]]


 [[[18 29]
   [22 26]]

  [[16 18]
   [27 26]]]] <class 'numpy.ndarray'>


In [8]:
# multi dimension array are used in image processing

In [9]:
a=np.random.randint(10,30,dtype=float)
print(a,type(a))

TypeError: Unsupported dtype dtype('float64') for randint

In [ ]:
# rand()---> generating random integer values between 0.0 and 1.0

"""  

"""
# randn()---> generating random integer values between 0.0 and 1.0 (normal distribution)
"""  

"""


In [10]:
a=np.random.uniform(1.5,2.9,size=(2,3,3,3))
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("dtype",a.dtype)

[[[[1.51524085 1.62183213 1.51084612]
   [1.68438233 1.70425405 2.12406422]
   [1.92161536 1.9718088  2.35204423]]

  [[1.98035264 2.62856018 2.25429841]
   [1.53667093 1.80676093 2.13584791]
   [2.8655215  2.53154155 2.10290377]]

  [[2.05646795 2.79958348 2.40566808]
   [2.26299241 2.50916316 2.57953147]
   [2.2296586  2.19497578 2.5152095 ]]]


 [[[2.4244942  2.13137871 1.80320333]
   [2.82520299 2.73170503 2.85697163]
   [2.72503967 1.9100031  2.0551468 ]]

  [[2.47494401 2.50595435 2.28944074]
   [1.99687535 1.81505567 2.73214266]
   [2.07091375 2.14405594 2.57120746]]

  [[2.73581673 1.88910781 2.7557907 ]
   [2.2287992  2.6508615  2.42922012]
   [1.99391818 1.75682761 2.44062949]]]] <class 'numpy.ndarray'>
dimension 4
shape (2, 3, 3, 3)
size 54
dtype float64
