In [2]:
import numpy as np

In [3]:
help(np.random.normal)

Help on method normal in module numpy.random:

normal(loc=0.0, scale=1.0, size=None) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)

    Draw random samples from a normal (Gaussian) distribution.

    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).

    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.

    .. note::
        New code should use the `~numpy.random.Generator.normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    loc : float or array_li

In [ ]:
#normal(loc=0.0,scale=1.0,size=6)

In [5]:
a=np.random.randint(1,101,size=(5,6))
print(a,type(a))

[[38 46 60 57 88 91]
 [33 41 90 57 41 10]
 [34 28 55 73 90 52]
 [24 66 50 71 42 58]
 [72 15 81 10 36 56]] <class 'numpy.ndarray'>


In [9]:
np.random.shuffle(a)
print(a)

[[24 66 50 71 42 58]
 [72 15 81 10 36 56]
 [38 46 60 57 88 91]
 [34 28 55 73 90 52]
 [33 41 90 57 41 10]]


In [11]:
a=np.arange(0,16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [12]:
a=np.arange(0,16).reshape(2,2,2,2)
print(a)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [13]:
help(np.hstack)

Help on _ArrayFunctionDispatcher in module numpy:

hstack(tup, *, dtype=None, casting='same_kind')
    Stack arrays in sequence horizontally (column wise).

    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.

    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.

    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length. In the case of a single
        array_like input, it will be treated as a sequence of arrays; i.e.,
        each element along the zeroth axis is treated as a separate array.

 

In [14]:
a=np.arange(13)
b=np.array_split(a,4)
print(b)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


In [ ]:
# 0:4 => 0 to 4-1
# 4:5 => 4 to 5-1


# spliting numpy 2d array