# NumPy index
- indexing is the process of obtaining single value from given iterable object.
- the values of iterable object contain +ve index and -ve index
- object of ndarray is also one of the iterable objects. also contain +ve and -ve index.
- in numpy  programmning , we can apply indexing operation on 3 types of array , they are :-
    - 1-D indexing
    - 2-D indexing
    - N-D indexing
________________________________________

# 1-D indexing
- syntax:-
    - 1darray[index]

    - here inding can be +ve  or -ve
    - if we enter valid index then we get corrosponding value from 1d array
    - if we enter invalid index then we get an IndexError.
    



In [2]:
# example on indexing operation
import numpy as np

In [8]:
a=np.array([10,20,30,40,50,60])
print("1.",a[3])
print("2.",a[-1])
print("3.",a[-6])
print("4.",a[len(a)-1])
print("5.",a[-len(a)])
print("6.",a[100])

1. 40
2. 60
3. 10
4. 60
5. 10


IndexError: index 100 is out of bounds for axis 0 with size 6

In [9]:
print("content of a=",a)
print("Dimension =",a.ndim)
print("shape=",a.shape)
print("size=",a.size)

content of a= [10 20 30 40 50 60]
Dimension = 1
shape= (6,)
size= 6


In [11]:
print("item size  of a=",a.itemsize)

item size  of a= 8


# 2D Indexing
- syntax:-
    - 2darray[row_index][col_index] 
    - or 
    - 2darray[row_index,col_index]

In [12]:
a=np.arange(16).reshape(4,4)
print(a,type(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>


In [13]:
# to get 5
a[1,1]

np.int64(5)

In [14]:
# to get 5
a[1][1]

np.int64(5)

In [15]:
# you can get via -ve indexing
a[-3,-3]

np.int64(5)

In [17]:
# to get 10
a[-2,-2]

np.int64(10)

# 3D indexing
$ or $
# ND indexing

- Syntax:-
    - ndarrayObject[matrixIndex,RowIndex,ColIndex]
    - ndarrayObject[matrixIndex],[rowIndex][colIndex]

In [19]:
a=np.arange(27).reshape(3,3,3)
print(a,type(a))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] <class 'numpy.ndarray'>


In [20]:
print("content of a=",a)
print("Dimension =",a.ndim)
print("shape=",a.shape)
print("size=",a.size)

content of a= [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimension = 3
shape= (3, 3, 3)
size= 27


In [22]:
# to get 4
a[0,1,1]

np.int64(4)

In [ ]:
#to get 4
a[-3,-2,-2]

np.int64(4)

In [ ]:
#to get 4
a[-3][-2][-2]

np.int64(4)

# Slicing:-
- 1D
- 2D
- 3D OR ND

In [25]:
a= np.array("mississippi")
print("content of a=",a)
print("Dimension =",a.ndim)
print("shape=",a.shape)
print("size=",a.size)

content of a= mississippi
Dimension = 0
shape= ()
size= 1


In [26]:
a= np.array(["mississippi"])
print("content of a=",a)
print("Dimension =",a.ndim)
print("shape=",a.shape)
print("size=",a.size)

content of a= ['mississippi']
Dimension = 1
shape= (1,)
size= 1


In [27]:
a= np.array(list("mississippi"))
print("content of a=",a)
print("Dimension =",a.ndim)
print("shape=",a.shape)
print("size=",a.size)

content of a= ['m' 'i' 's' 's' 'i' 's' 's' 'i' 'p' 'p' 'i']
Dimension = 1
shape= (11,)
size= 11


- the process of obtaining range of values or sub values from an oterable object is called slicing.
- we can apply slicing operations on 3 type of ndarray. they are 
    - 1-D array
    - 2-D array
    - 3-D array /ND array

# 1D array:-
- syntax:- adarray[begin:end]
    - gives range of values from the begin index to end-1 index provided begin<end
    - syntax:- adarray[begin:]
    - syntax:- adarray[:end]
    - syntax:- adarray[:]
    - syntax:- adarray[begin:end:step]


In [28]:
# 2 D array