# NumPy, Pandas, Matplotlib

- NumPy
- creation of numpy array
- array()
- arange()
- linspace()
- zeros()
- Ones()
- full()
- eye()
- identity()
- diag()
- empty()
- random library function

- randint()
- rand()
- uniform()
- randn()
- normal()
- shuffle()
-------------------------

- Array attributes & numpy data types
- view vs copy

------------------

- Indexing, Slicing and advance Indexing
- basic indexing- to select only one element
- slicing - to select multiple arbitrary element
- condition based selection

------------------

- how to iterate element of the nd array

- by python loop
- by numpy nditer() function
- by using ndenumerate() function

------------------

Arithmetics operation:
- arithmetics operation for numpy array with scaler
- arithmetics operation for array with array


----------------------
Array manipulation function

- reshape()
- resize() 
- flatten()
- flat variable
- ravel()
- transpose()
- swapaxes()


--------------
- Joining of multiple array into a single array

- concatenate()
- stack()
- vstack()
- hstack()
- dstack()

--------------
- splitting of array 

- split()
- vsplit()
- hsplit()
- dsplit()

--------------
- how to insert element from ndarray

- insert()
- append()

---------------

- deleting element from ndarray
- matrix multiplication
- importance of matrix class in numpy library.

--------------
- Linear algebra function from linalg module
- inv() - to find the inverse of matrix
- matrix_power() - to find the power of matrix A^n
- det() - to find the determinant of matrix
- solve() - to solve the linear algebra question
-  I/O  operation with numpy 
- basic statistics with numpy
- numpy mathematics function
- how to find unique items and count.


In [443]:
"""
Pre requisite-
 Data type
 loop
 function
 
"""

'\nPre requisite-\n Data type\n loop\n function\n \n'

- Numpy stand for numerical python 
- to deal with arrays based computing + complex operation
- travis oliphan developed numpy 
- he developed numpy in C, Python language.

In [444]:
lst=[[10,20],[30,40]]
print(lst)

[[10, 20], [30, 40]]


In [445]:
for row in lst:
    print(row)

[10, 20]
[30, 40]


In [446]:
""""
- ndarray - mean n dimension array
- pip install numpy

- to uninstall
pip uninstall numpy

# to install and uninstall you need internet connection
because pip is connected to github

-to find the version of numpy
import numpy
print(np.__version__)

"""

'"\n- ndarray - mean n dimension array\n- pip install numpy\n\n- to uninstall\npip uninstall numpy\n\n# to install and uninstall you need internet connection\nbecause pip is connected to github\n\n-to find the version of numpy\nimport numpy\nprint(np.__version__)\n\n'

In [447]:
import numpy as np
print(np.__version__)



2.2.2


In [448]:
lst=[10,20,30,40,50,60,15,10,35,20,30]
a=np.array(lst)
print(a,type(a))

[10 20 30 40 50 60 15 10 35 20 30] <class 'numpy.ndarray'>


In [449]:
a=a+1
print(a,type(a))

[11 21 31 41 51 61 16 11 36 21 31] <class 'numpy.ndarray'>


In [450]:
# how to find the memory size 
import sys
lst1=[10,20,30]
print(sys.getsizeof(lst1))

88


In [451]:
# vector based operation is done with numpy.
# nd array take less memory space for large scale data 
#

# Numpy

"""  
- numpy stand for numerical python .
- numpy is one of the pre define third party module / library and numpy module is not pre define module in python.
- syntax for installing any module in python:
    pip install numpy
    
- to use numpy as a part of our program , we must import numpy module.
- a numpy module is collection of variable, function, and classes.
____________________

History of numpy:-

- developed in 2005 by travis oliphan.
- to solve complex math.
- numpy is developed in c and python language.

- in numpy programming , data is organise in the object of "ndarray". which is one of the pre defined class in numpy.
- hence object of ndarray can store same type or different type ( unique+duplicate ) in single object.

__________________________

# Advantage of numpy.

- with revolution of data science , data analysis like numpy, scipy, scikit and pandas etc., have seen a lot of growth.
- numpy provide a convenient and efficient way to handle the vast amount of data .
- numpy can also do matrix operation and data reshaping.
- numpy is fast which makes it resonable to work with large set of data.


- we can perform 1d,2d ,3d multi dimension array.
- numpy maintain minimal memory for large of data .
-  numpy provide fast in performing operation because it internally its data is available at same address.
- numpy provide many inbuilt function for various complex mathematics operation such as statistical, algebraic, trigonometric, financial and many more.
    
"""

# number of ways to create an object of ndarray:-

 
# i want to create a object of list:-
- lst1=list()
#or
- lst2=[]
#or 
- lst3=list({v1,v2,v3})
#or
lst4=list((v1,v2,v3))


In [452]:
# in numpy we can create an object of ndarray with the following ways:-

#1. array()
#2. arange()
#3. linspace()
#4. zeros()
#5. ones()
#6. full()
#7. identity()
#8. eye()
#9. hstack()
#10. vstack()


#numpy.random 
    #a. randint()
    #b. rand()
    #c. uniform()
    #d. randn()
    #e. normal()
    #f. shuffle()
    

In [453]:
#pip show numpy
#pip list

# 1. array()
- syntax:-
- varname=numpy.array(object,dtype)
- this function is used  for converting traditional python objects into ndarray object



In [454]:
import numpy as np
b=90
a=np.array(b)
print(a,type(a))

90 <class 'numpy.ndarray'>


In [455]:
print(a.ndim)

0


In [456]:
print(a.shape)

()


In [457]:
print(a.size)

1


In [458]:
print(a.dtype)

int64


In [459]:
b=3.4
a=np.array(b)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

3.4 <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type float64


In [460]:
b=3.4+4.5j
a=np.array(b)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

(3.4+4.5j) <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type complex128


In [461]:
b="python"
a=np.array(b)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

python <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type <U6


In [462]:
for val in range(1,11):
    print(val,end="\t")

1	2	3	4	5	6	7	8	9	10	

In [463]:
r=range(10,51,2)
a=np.array(r)
print(a,end="\t")

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]	

In [464]:
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50] <class 'numpy.ndarray'>
dimension 1
shape (21,)
size 21
internal data type int64


In [465]:
a=np.array(range(6),dtype=bool)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[False  True  True  True  True  True] <class 'numpy.ndarray'>
dimension 1
shape (6,)
size 6
internal data type bool


In [466]:
a=np.array(range(6),dtype=int)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[0 1 2 3 4 5] <class 'numpy.ndarray'>
dimension 1
shape (6,)
size 6
internal data type int64


# now i want to reshape the 1D to 2D array:-

- syntax: for shape attribute
- ndarrayobj.shape=(rows,cols)
-  syntax: for reshape attribute
- ndarrayobj=ndarrayobj.reshape(rows,cols)

In [467]:
a=np.array(range(100,156,5))
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
dimension 1
shape (12,)
size 12
internal data type int64


In [468]:
a.shape=(4,3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[100 105 110]
 [115 120 125]
 [130 135 140]
 [145 150 155]] <class 'numpy.ndarray'>
dimension 2
shape (4, 3)
size 12
internal data type int64


In [469]:
a.shape=(12,)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
dimension 1
shape (12,)
size 12
internal data type int64


In [470]:
a.reshape(4,3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
dimension 1
shape (12,)
size 12
internal data type int64


In [471]:
a=a.reshape(12,)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
dimension 1
shape (12,)
size 12
internal data type int64


In [472]:
a=np.array(range(0,16))
a.shape=(2,2,2,2)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]] <class 'numpy.ndarray'>
dimension 4
shape (2, 2, 2, 2)
size 16
internal data type int64


In [473]:
lst=[10,20,30,40,50,60,70,80,90,100,110,120,130,140,160]
a.shape=(4,4)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>
dimension 2
shape (4, 4)
size 16
internal data type int64


In [474]:
a.shape=(2,2,4)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] <class 'numpy.ndarray'>
dimension 3
shape (2, 2, 4)
size 16
internal data type int64


In [475]:
# to flatten
a.shape=(16,)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] <class 'numpy.ndarray'>
dimension 1
shape (16,)
size 16
internal data type int64


In [476]:
s1={10,20,30,40,50,60}
print(s1,type(s1))

{50, 20, 40, 10, 60, 30} <class 'set'>


In [477]:
a=np.array(s1)

print(a,type(a))

{50, 20, 40, 10, 60, 30} <class 'numpy.ndarray'>


In [478]:
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

{50, 20, 40, 10, 60, 30} <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type object


In [479]:
d1={10:"python",20:"java",30:"c",40:"c++"}

a=np.array(d1)
print(a,type(a))
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

{10: 'python', 20: 'java', 30: 'c', 40: 'c++'} <class 'numpy.ndarray'>
{10: 'python', 20: 'java', 30: 'c', 40: 'c++'} <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type object


# 2. arange()
- arange() is used for generating range of values with equal interval of value(default interval value or step value is 1)
- syntax:-
- varname=numpy.arange(start)
- varname=numpy.arange(start,end)
- varname=numpy.arange(start,end,step)

- arange() by default create an object of ndarray with 1D  array only ,it cannot built 2D and n-dimension array

- to built 2D and n-D array from arange() function we use reshape() or shape attribute.
 

In [480]:
import numpy as np
a=np.arange(10)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
dimension 1
shape (10,)
size 10
internal data type int64


In [481]:
a.shape=(5,2)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] <class 'numpy.ndarray'>
dimension 2
shape (5, 2)
size 10
internal data type int64


In [482]:
a=np.arange(10,22)
print(a,type(a),len(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[10 11 12 13 14 15 16 17 18 19 20 21] <class 'numpy.ndarray'> 12
dimension 1
shape (12,)
size 12
internal data type int64


In [483]:
a.shape=(2,2,3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]] <class 'numpy.ndarray'>
dimension 3
shape (2, 2, 3)
size 12
internal data type int64


In [484]:
a=np.arange(10,22).reshape(2,3,2)
print(a,type(a))

[[[10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]]] <class 'numpy.ndarray'>


In [485]:
a=np.arange(10,106,5).reshape(5,4)
print(a,type(a),len(a))

[[ 10  15  20  25]
 [ 30  35  40  45]
 [ 50  55  60  65]
 [ 70  75  80  85]
 [ 90  95 100 105]] <class 'numpy.ndarray'> 5


# linspace()
- syntax:-
- varname=numpy.linspace(start,stop,num,endpoint,restep,dtype)
- 

In [486]:
a=np.linspace(1,2)

print(a,type(a))

[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ] <class 'numpy.ndarray'>


In [487]:
a=np.linspace(1,2,num=5)
print(a,type(a))

[1.   1.25 1.5  1.75 2.  ] <class 'numpy.ndarray'>


In [488]:
a=np.linspace(1,2,num=5,endpoint=False)
print(a,type(a))

[1.  1.2 1.4 1.6 1.8] <class 'numpy.ndarray'>


In [489]:
a=np.linspace(1,2,num=5,retstep=True)
print(a,type(a))

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), np.float64(0.25)) <class 'tuple'>


# zeros()
- syntax:-
- varname=numpy.zeros(shape,dtype)

In [490]:
l1=[0,0,0,0]
a=np.array(l1)
print(a,type(a))
a.shape=(2,2)
print(a,type(a))

[0 0 0 0] <class 'numpy.ndarray'>
[[0 0]
 [0 0]] <class 'numpy.ndarray'>


In [491]:
a=np.zeros((2,2),dtype=int)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[[0 0]
 [0 0]] <class 'numpy.ndarray'>
dimension 2
shape (2, 2)
size 4
internal data type int64


In [492]:
a=np.zeros((3,3,3),dtype=int)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]] <class 'numpy.ndarray'>
dimension 3
shape (3, 3, 3)
size 27
internal data type int64


# ones()
- syntax:-
- 

In [493]:
a=np.ones(3,dtype=int)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[1 1 1] <class 'numpy.ndarray'>
dimension 1
shape (3,)
size 3
internal data type int64


In [494]:
a=np.ones((2,3,4),dtype=int)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)
#a= numpy.ones((dimension,rows,columns),dtype=int)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] <class 'numpy.ndarray'>
dimension 3
shape (2, 3, 4)
size 24
internal data type int64


# full()
- syntax:-
- varname=numpy.full(shape,fill_value,dtype)


In [495]:
a=np.full(6,9)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[9 9 9 9 9 9] <class 'numpy.ndarray'>
dimension 1
shape (6,)
size 6
internal data type int64


In [496]:
a=np.full(6,9).reshape(2,3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[[9 9 9]
 [9 9 9]] <class 'numpy.ndarray'>
dimension 2
shape (2, 3)
size 6
internal data type int64


In [497]:
a=np.full((3,3),6)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[[6 6 6]
 [6 6 6]
 [6 6 6]] <class 'numpy.ndarray'>
dimension 2
shape (3, 3)
size 9
internal data type int64


In [498]:
a=np.full((3,3,3),6)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[[6 6 6]
  [6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]]] <class 'numpy.ndarray'>
dimension 3
shape (3, 3, 3)
size 27
internal data type int64


In [499]:
a=np.full((3,3,3),"itty")
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']]

 [['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']]

 [['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']]] <class 'numpy.ndarray'>
dimension 3
shape (3, 3, 3)
size 27
internal data type <U4


# identity()
- syntax:-
- varname=numpy.identity(N,dtype)

In [500]:
a=np.identity(3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <class 'numpy.ndarray'>
dimension 2
shape (3, 3)
size 9
internal data type float64


# eye()

- varname= numpy.eye(N,M=none,k=0,dtype)

In [501]:
a= np.identity(5,dtype=int)
print(a,type(a))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] <class 'numpy.ndarray'>


In [502]:
a= np.eye(5,dtype=int)
print(a,type(a))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] <class 'numpy.ndarray'>


In [503]:
a= np.eye(5,k=-1,dtype=int)
print(a,type(a))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]] <class 'numpy.ndarray'>


In [504]:
a= np.eye(5,k=-2,dtype=int)
print(a,type(a))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]] <class 'numpy.ndarray'>


In [505]:
a= np.eye(3,5,dtype=int)
print(a,type(a))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]] <class 'numpy.ndarray'>


In [506]:
a= np.eye(5,3,dtype=int)
print(a,type(a))

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]] <class 'numpy.ndarray'>


# Random number generation in numpy:-
- numpy.random
- 1. randint()
- 2. rand()
- 3. uniform()
- 4. randn()
- 5. normal()
- 6. shuffle()


- --> these are very much useful data science algorithm.(random number generation in numpy:-)

In [507]:
import numpy as np
""" 
_____________________________________  
 1. randint() :- 
 syntax:-
 randint(low, high=None, size=None, dtype=int)
_____________________________________
- 2. rand()
_____________________________________
- 3. uniform()
_____________________________________
- 4. randn()
_____________________________________
- 5. normal()
_____________________________________
- 6. shuffle()
_____________________________________



"""


' \n_____________________________________  \n 1. randint() :- \n syntax:-\n randint(low, high=None, size=None, dtype=int)\n_____________________________________\n- 2. rand()\n_____________________________________\n- 3. uniform()\n_____________________________________\n- 4. randn()\n_____________________________________\n- 5. normal()\n_____________________________________\n- 6. shuffle()\n_____________________________________\n\n\n\n'

In [508]:
a=np.random.randint(10)
print(a,type(a))

0 <class 'int'>


In [509]:
a=np.random.randint(10,30,size=(10,20))
print(a,type(a))

[[28 15 15 13 28 13 27 24 15 24 18 22 16 27 11 21 19 15 20 10]
 [15 20 10 28 19 26 14 16 22 13 23 20 12 25 23 17 16 11 20 14]
 [19 29 26 18 27 28 24 27 29 16 23 24 27 17 11 13 23 29 11 27]
 [18 21 16 11 20 28 12 15 26 26 22 13 14 18 25 11 21 21 24 10]
 [10 16 17 20 20 21 21 20 28 15 12 26 27 21 28 16 29 29 27 27]
 [19 17 11 18 17 11 10 20 21 11 20 23 19 10 22 21 14 12 23 26]
 [15 19 19 26 20 27 24 19 22 12 10 19 20 24 19 10 12 28 11 13]
 [12 16 20 20 20 17 21 16 27 26 28 10 23 11 10 16 10 19 27 15]
 [12 22 21 10 16 14 19 13 23 25 21 22 16 19 29 28 19 15 26 12]
 [13 21 19 26 14 20 19 22 16 19 19 14 21 20 26 24 26 23 19 18]] <class 'numpy.ndarray'>


In [510]:
a=np.random.randint(10,30,size=(3,3,3))
print(a,type(a))

[[[14 14 11]
  [21 27 26]
  [15 21 22]]

 [[12 19 22]
  [25 27 20]
  [26 25 25]]

 [[17 15 13]
  [20 24 14]
  [21 10 10]]] <class 'numpy.ndarray'>


In [511]:
a=np.random.randint(10,30,size=(2,2,2,2))
print(a,type(a))

[[[[12 18]
   [22 27]]

  [[16 23]
   [18 10]]]


 [[[12 14]
   [19 19]]

  [[17 11]
   [22 19]]]] <class 'numpy.ndarray'>


In [512]:
# multi dimension array are used in image processing

In [513]:
a=np.random.randint(10,30,dtype=float)
print(a,type(a))

TypeError: Unsupported dtype dtype('float64') for randint

In [ ]:
# rand()---> generating random integer values between 0.0 and 1.0

"""  

"""
# randn()---> generating random integer values between 0.0 and 1.0 (normal distribution)
"""  

"""


In [ ]:
a=np.random.uniform(1.5,2.9,size=(2,3,3,3))
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("dtype",a.dtype)

In [ ]:
import numpy as np
a=np.random.randint(1,101,size=(5,6))
print(a,type(a))

In [ ]:
np.random.shuffle(a)
print(a)

In [ ]:
a=np.arange(0,16).reshape(4,4)
print(a)

In [ ]:
a=np.arange(0,16).reshape(2,2,2,2)
print(a)

In [ ]:
help(np.hstack)

In [ ]:
a=np.arange(13)
b=np.array_split(a,4)
print(b)

In [ ]:
# 0:4 => 0 to 4-1
# 4:5 => 4 to 5-1


# NumPy index
- indexing is the process of obtaining single value from given iterable object.
- the values of iterable object contain +ve index and -ve index
- object of ndarray is also one of the iterable objects. also contain +ve and -ve index.
- in numpy  programmning , we can apply indexing operation on 3 types of array , they are :-
    - 1-D indexing
    - 2-D indexing
    - N-D indexing
________________________________________

# 1-D indexing
- syntax:-
    - 1darray[index]

    - here inding can be +ve  or -ve
    - if we enter valid index then we get corrosponding value from 1d array
    - if we enter invalid index then we get an IndexError.
    



In [ ]:
# example on indexing operation
import numpy as np

In [ ]:
a=np.array([10,20,30,40,50,60])
print("1.",a[3])
print("2.",a[-1])
print("3.",a[-6])
print("4.",a[len(a)-1])
print("5.",a[-len(a)])
print("6.",a[100])

In [ ]:
print("content of a=",a)
print("Dimension =",a.ndim)
print("shape=",a.shape)
print("size=",a.size)

In [ ]:
print("item size  of a=",a.itemsize)

# 2D Indexing
- syntax:-
    - 2darray[row_index][col_index] 
    - or 
    - 2darray[row_index,col_index]

In [ ]:
a=np.arange(16).reshape(4,4)
print(a,type(a))

In [ ]:
# to get 5
a[1,1]

In [ ]:
# to get 5
a[1][1]

In [ ]:
# you can get via -ve indexing
a[-3,-3]

In [ ]:
# to get 10
a[-2,-2]

# 3D indexing
$ or $
# ND indexing

- Syntax:-
    - ndarrayObject[matrixIndex,RowIndex,ColIndex]
    - ndarrayObject[matrixIndex],[rowIndex][colIndex]

In [ ]:
a=np.arange(27).reshape(3,3,3)
print(a,type(a))

In [ ]:
print("content of a=",a)
print("Dimension =",a.ndim)
print("shape=",a.shape)
print("size=",a.size)

In [ ]:
# to get 4
a[0,1,1]

In [ ]:
#to get 4
a[-3,-2,-2]

In [ ]:
#to get 4
a[-3][-2][-2]

# Slicing:-
- 1D
- 2D
- 3D OR ND

In [ ]:
a= np.array("mississippi")
print("content of a=",a)
print("Dimension =",a.ndim)
print("shape=",a.shape)
print("size=",a.size)

In [ ]:
a= np.array(["mississippi"])
print("content of a=",a)
print("Dimension =",a.ndim)
print("shape=",a.shape)
print("size=",a.size)

In [ ]:
a= np.array(list("mississippi"))
print("content of a=",a)
print("Dimension =",a.ndim)
print("shape=",a.shape)
print("size=",a.size)

- the process of obtaining range of values or sub values from an iterable object is called slicing.
- we can apply slicing operations on 3 type of ndarray. they are 
    - 1-D array
    - 2-D array
    - 3-D array /ND array

# 1D array:-
- syntax:- ndarray[begin:end]
    - gives range of values from the begin index to end-1 index provided begin<end
    - syntax:- adarray[begin:]
    - syntax:- adarray[:end]
    - syntax:- adarray[:]
    - syntax:- adarray[begin:end:step]


# syntax for 2D slicing:-
- 2DArrayObj[rowbegin:rowend:rowstep,colbegin:colend,colStep[]]

In [ ]:
import numpy as np
a=np.arange(16).reshape(4,4)
print(a,type(a))

In [ ]:
a[0:4,0:1]

In [ ]:
a[:,0:1]

In [ ]:
a[::,:1]

In [ ]:
# want 4,5,8,9
a[1:3,0:2]

In [ ]:
a[1:4,1:4]

In [ ]:
a[1:3,0:4]

In [ ]:
a[1:3,:]

In [ ]:
a[1:3,::]

In [ ]:
# with step value
a[0:4:2,0:4]

In [ ]:
a[-2:,-2:]

In [ ]:
# its not possible t get principle element by using regular indexing and slicing operations
# you can get diagonal element via advance indexing method.
 

In [ ]:
a=np.arange(27).reshape(3,3,3)
print(a)

In [ ]:
"""3D array"""
# [matrixBegin:matrixEnd:matrixStep,rowBegin:rowEnd:rowStep,colBegin:colEnd:colStep]

In [ ]:
a[0:2,0:1,0:2]

In [ ]:
a[:2,:1,:2]

In [ ]:
a[:,::2,0:1]

In [ ]:
a[::2,2:3,::2]

In [ ]:
# want corner element
a[:,::2,::2]

In [ ]:
# to convert 3d to 1d
# use ravel and flaten

In [ ]:
"""with slicing operation , we cant get random element 
- for getting random element , we must learn advance indexing and slicing.

"""

# Advance indexing and slicing
- 2D advance indexing:-
identify the row indices of random element
- syntax : rowindices=(row1,row2,row3..row-n)
- identify the column indices of random element
- syntax : columnindices=(col1,col2,col3..col-n)

- pass the row indices and colindices to original

In [ ]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
a.shape=(3,3)
print(a,type(a))

In [ ]:
# to get diagonal element (10,50,90)
rowindices=(0,1,2)# step1
colindices=(0,1,2)#step2
# a[rowindices,colindices]

In [ ]:
#get reverse diagonal element
print(a)
a[(0,1,2),(2,1,0)]

In [ ]:
print(a)
a[(0,1,2,2)(1,1,2,0)] # internally process as a[(0,1),(1,1),(2,2),(2,0)]

# Numpy filtering the data
- 1D,2D,3D or conditional based retrieval from 1D,2D,3D

In [ ]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)


In [ ]:
a.shape=(9,)
print(a)

In [ ]:

""" 
- procedure-1:-
step1:
create a boolean array
_____________________
step2:-
pass boolean to ndarray
__________

"""

In [ ]:
# get the multiple of 3
ba=a%3==0
print(ba,type(ba))

In [ ]:
# pass the boolean to ndarray object
a[ba]

In [ ]:
# get the multiple of 4
a[a%4==0]

In [ ]:
a=np.array([[10,-20,-30],[40,-50,60],[70,-80,-90]])
print(a,type(a))

In [ ]:
#get all positive value
pa=a[a>0]
print(pa,type(pa))

In [ ]:
#get all the negative value
na=a[a<0]
print(na,type(na))

# numpy copy vs view
- copy()
- view()

In [ ]:
a=np.array([10,20,30,40])
print(a,type(a))

In [ ]:
b=a.copy()
print("original array = {} and {}".format(a,type(a)))
print("copied array = {} and {}".format(b,type(b)))


In [ ]:
a[0]=100
print("original array = {} and {}".format(a,type(a)))
print("copied array = {} and {}".format(b,type(b)))

# view()

In [ ]:
b=a.view()
print("original array = {} and {}".format(a,type(a)))
print("copied array = {} and {}".format(b,type(b)))

In [ ]:
# it is just deep copy changes on one will affect the others

In [ ]:
# arithmetic operation on ndarray
#or
#arithmetic operation
"""   
+
-
*
/
//
%
**

 """

In [ ]:
import numpy as np
help(np.ones)

In [ ]:
import numpy as np
a=np.array([[10,20],[30,40]])
b=np.array([[1,2],[3,4]])
c=np.power(a,b)
print(c)

In [ ]:
# another method
d=a**b
print(d)

In [ ]:
e=a/b
print(e)

In [ ]:
a=np.array([[10,20],[30,40]])
b=np.array([[0,1],[2,3]])
c=a/b
print(c)

In [ ]:
#inf20  mean infinity 
# how to deal with  it 

In [ ]:
c[0,0]

In [ ]:
c[0,0]="can't divide by zero"

In [ ]:
d=c.astype(str)
print(d)

In [ ]:
d[0,0]="can't divide by zero"
print(d)

In [ ]:
e=d.astype(object)
print(e)

In [ ]:
e.dtype

# where

In [ ]:
a=np.array([10,20,30,10,40,10,20,30])
b=np.where(a==10)
print(b)

In [ ]:
s="mississippi"
a=np.array(list(s))
print(a)

In [ ]:
np.where(a=="s")

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

In [ ]:
ind=np.where(a==4)
print(ind)

In [ ]:
ind=np.where(a%3==0)
print(ind)

In [ ]:
# find the element which are not multiple of 3


# NumPy iteration
- 1D
- 2D
- 3D

- nditer()
- ndenumerate()


In [ ]:
import numpy as np
a = np.array([10,20,30,40,50,60,70,80])
print(a,type(a),id(a))

In [ ]:
# display the element of ndarrray using for loop
for val in a:
    print(val)

In [ ]:
# display the element of ndarray by using while loop
i=0
while(i<len(a)):
    print(a[i])
    i=i+1

In [ ]:
a=np.arange(16).reshape(4,4)
print("content of a\n",a)
print("dimension",a.ndim)
print("shape",a.shape)

In [ ]:
for i in a:
    print(i)

In [ ]:
for row in a:
    for colelement in row:
        print(colelement)

In [ ]:
a=np.arange(16).reshape(2,4,2)
print("content of a\n",a)
print("dimension",a.ndim)
print("shape",a.shape)

In [ ]:
for matrix in a:
    for row in matrix:
        for colemement in row:
            print(colemement)
        

- In numpy we have 2 function to iterate the element of ndarray
1. nditer()
2. ndenumerate()

In [ ]:
# nditer()
import numpy as np
a = np.array([10,20,30,40,50,60,70,80,90])
for val in np.nditer(a):
    print(val)

In [ ]:
a.shape=(3,3)
print(a)

In [ ]:
# displaying 2d
for val in np.nditer(a):
    print(val)

In [ ]:
a=np.array([10,20,30,40,50,60,70,80,90,100,110,120])
a.shape=(2,3,2)
print(a)

In [ ]:
# diplay 3d
for val in np.nditer(a):
     print(val)

In [ ]:
# using ndenumerate
for index,value in np.ndenumerate(a):
    print(index,"-->",value)

In [ ]:
# index start with 0 but you want to start it with 1
a = np.array([10,20,30,40,50,60,70,80,90])
for i,v in np.ndenumerate(a):
    print("{}-->{}".format(i[0]+1,v))

In [ ]:
# the above is called program define index

In [ ]:
"""  
=> random.rand()
=> random.uniform()- uniform distribution
=> random.randn()
=> random.normal()-normal distribution

_______________________

# data distribution in numpy
- possibility of occurence of value
- value of occurence in list.

_____________________

probability 
"""

In [ ]:
# numpy random data distribution
a=np.array([3,5,7,9])
x=np.random.choice(a,p=[0.1,0.3,0.6,0.0],size=(100))
print(x)

In [ ]:
print(x.size)

In [ ]:
import random as r
lst=[10,20,30,40,50,60]
r.shuffle(lst)
print(lst)

In [ ]:
for i in range(len(lst)):
    r.shuffle(lst)
    print(lst)

In [ ]:
s="mississippi"
""" 
shuffle cannot apply on str,byte ,tuple,range,set,frozenset ,dict ,since they are immutable in nature
"""

In [ ]:
s="mississippi"
lst=list(s)
for i in range(len(lst)):
    r.shuffle(lst)
    print(''.join(lst))

In [ ]:
# example on numpy permutation and combination by numpy.random.shuffle and permutation .


# NumPy random permutation of elements
- a permutation refer to an arrangement of element eg: [3,2,1] is a permuataion of [1,2,3] and vice versa 
- NumPy random module provide two method for this 
1. shuffle() and
2. permutation()

In [ ]:
a=np.array([10,20,30,40,50,])
print("original ndarray object=",a)

In [ ]:
# re-arrange the elements of ndarray
np.random.shuffle(a)
print(a)

In [ ]:
for i in range(len(a)):
    np.random.shuffle(a)
    print(a)

# generating permutation of array
- the permutation method return a re-arranged array (leaves the original array unchanged)

In [ ]:
# by using permutation  for re-arranging elements
arr=np.array([1,2,3,4,5])
print(np.random.permutation(arr))

In [ ]:
arr=np.array(list("mississippi"))
x=np.random.permutation(arr)
print(x)

In [ ]:
arr=np.array(list("mississippi"))
for i in range(len(arr)):
    x=np.random.permutation(arr)
    print(x)

In [ ]:
print("".join(x))

# flatten() and ravel()

In [ ]:
a=np.arange(9).reshape(3,3)
print(a)
print("dimension=",a.ndim)
print("shape=",a.shape)


In [ ]:
# now make it flatten 
a.shape=(9,)
print(a)

In [ ]:
a=np.arange(9).reshape(3,3)
print(a.flatten())
print("dimension=",a.ndim)
print("shape=",a.shape)


In [ ]:
""" 
-->numpy is made from "C" and "FORTRAN"
--> "C"- stand for column measure 
--> "FORTAN" - stand for formula translation 
"""

In [ ]:
a=np.arange(9).reshape(3,3)
print("given array")
print(a)
print("-------------------------------")
x=a.flatten("F")
print("content of x=",x)
print("dimension=",x.ndim)
print("shape=",x.shape)



In [ ]:
# column become row
# row become column


In [ ]:
a=np.arange(9).reshape(3,3)
print("given array")
print(a.ravel())


In [ ]:
# example of numpy swaping 

In [ ]:
import numpy as np
# create array with shape(4,3)
my_array=np.arange(12).reshape(4,3)
print("original array:")
print(my_array)
# swaping the column with index of original array
my_array[:,[2,0]]=my_array[:,[0,2]]
print("after swaping the array the last column and first column :")
print(my_array)

In [ ]:
# function defination for swap

""" 
import numpy as np
# creating array
def swap(arr,startIndex,lastIndex):
     arr[:,[startIndex,lastIndex]]=arr[lastIndex,startIndex]
   
"""

# Numpy statistics operation:-
1. amax()
2. amin()
3. mean()
4. median()
5. mode() not present in python module
6. var() # variance 
7. std() # standard deviation

In [ ]:
# 1d array
a=np.array([10,20,3,5,14,-6,26])
print(np.amax(a))
print(np.amin(a))


In [ ]:
# 2d array related row max and col max
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(np.amax(a))
print(np.amin(a))
print(np.amax(a,axis=0))
print(np.amax(a,axis=1))

In [ ]:
# find the mean 
lst=[10,20,30,40,50,60,70,80,90,100]
s=0
for val in lst:
    s=s+val
    
print(":sum=",s)
print("mean or average=",(s/len(lst)))
print("using pre define function:",(sum(lst)/len(lst)))

In [ ]:
# finding mean of 1D array
a=np.array([10,20,30,40,50,60,70,80,90,100])
print("content of a",a)
print("mean of 1D array",np.mean(a))


In [ ]:
# finding mean of 2D array

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)
print("mean of 2D array",np.mean(a))
print("mean of 2D array along axis 0",np.mean(a,axis=0))
print("mean of 2D array along axis 1",np.mean(a,axis=1))

In [ ]:
""" 
0 axis mean = y axis or vertical axis or column
1 axis mean = x axis or horizontal axis or row

"""

In [ ]:
# finding median of 1D array
sals=[12,35,24,6,36,8,9]
asals=np.array(sals)
print("list of average salary",asals)
mdsal=np.median(asals)
print(mdsal)
print("mean sal",np.mean(asals))

In [ ]:
# find the median of 2-d array with number of values
import numpy as np
a=np.array([[10,2,20],[5,15,8],[5,15,4]])
print(a)
print("median",np.median(a))
print("median of 2d array",np.mean(a))



In [ ]:
# print(np.mode)
# we dont have mode in numpy

# Finding variance

In [ ]:
import numpy as np
a=np.array([[2,4],[1,3]])
print(a,type(a))

In [ ]:
# calculating mean
print(np.mean(a))

In [ ]:
# total variance of a
print("variance of a=",np.var(a))

In [ ]:
# column variance of a
print("column variance of a=",np.var(a,axis=0))

In [ ]:
# row variance of a
print("column variance of a=",np.var(a,axis=1))

# standard deviation
# standard deviation =math.sqrt(variance)

In [ ]:
# total variance
print(np.std(a))

In [ ]:
# colummn variance
print(np.std(a,axis=0))

In [ ]:
# row variance
print(np.std(a,axis=1))

# concept of mode via statistics

In [ ]:
import statistics as s
lst=[10,20,30,10,40,50,20,10,15]
print(s.mode(lst))

In [ ]:
# mode give most frequent/occurence element

In [ ]:
# to find multi frequent element 
lst=[10,20,30,10,40,30,50,20,10,15,20,20,10,15,30,30]
print(s.multimode(lst))

In [ ]:
import numpy as np
a=np.array(list("mississippi"))
print(s.multimode(a))

# ndarray with appending,insert,delete operation

In [ ]:
# append()
a=np.array([10,20,30,40])
print(a,type(a))

In [ ]:
np.append(a,100)

In [ ]:
# appending multiple values to ndarray object   
a=np.append(a,[50,60,70,80,90,100])
print(a)

In [ ]:
# append function with 2d
a=np.array([[10,20],[30,40]])
print(a)

In [ ]:
a=np.append(a,[[50,60],[70,80]],axis=0)
print(a)

In [ ]:
a=np.append(a,[[50,60],[70,80]],axis=0)
print(a)

In [ ]:
# column
a=np.append(a,[[0,0]],axis=0)
print(a)

In [ ]:
a=np.append(a,[[0],[0],[1],[1],[0]],axis=1)
print(a)

# insert operation on ndarray

In [ ]:
a=np.array([10,20,30,40,50,60])
print(a)

In [ ]:
print(a,1,15)

In [ ]:
a=np.insert(a,1,15)
print(a)

In [ ]:
a=np.insert(a,3,[11,22,33,44])
print(a)

In [ ]:
a=np.array([10,20,30,40,50,60,70,80,90])
print(a)

In [ ]:
a.shape=(3,3)
print(a)

In [ ]:
print(np.insert(a,1,[11,22,33],axis=0))

In [ ]:
print(np.insert(a,1,[44,55,66],axis=1))

# delete

In [ ]:
print(np.delete(a,[0,-2]))

In [ ]:
a=np.arange(5*5).reshape(5,5)
print(a)

In [ ]:
a=np.delete(a,2,axis=0)
print(a)

In [ ]:
a=np.arange(5*5).reshape(5,5)
print(a)

In [ ]:
a=np.delete(a,1,axis=1)
print(a)

In [ ]:
# axis =1 mean column
# axis =0 mean row

In [ ]:
import numpy as np
a=np.arange(25).reshape(5,5)
print(a)

In [ ]:
import numpy as np
import statistics as s
a=np.arange(25).reshape(5,5)
print(a)

In [ ]:
# to delete complete array
del a

In [ ]:
print(a)

In [ ]:
a=np.arange(5*5).reshape(5,5)
print(a)

In [ ]:
a=np.delete(a,[int(i) for i in range(a.shape[0])],axis=1)
print(a)

# universal function
- add()
- subtract()
- multiply()
- divide()
- floor_divide()
- mod()
- power()
- remainder()
- divmod() q=[] r=[]


In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(np.multiply(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.add(arr1, arr2))
print(np.divide(arr1, arr2))


In [ ]:
arr=np.around(3.16666)
print(arr)

In [ ]:
arr=np.array([3,6,9])
x=np.lcm.reduce(arr)
print(x)

In [ ]:
# numpy gcd greatest common denominator
arr=np.array([20,8,32,16])
x=np.gcd.reduce(arr)
print(x)

# numpy sorting data

In [ ]:
a=np.array([10,2,13,4,-5,0,16,25,-16])
print(a)
# to sort the data 
print(np.sort(a))

In [ ]:
a.shape=(3,3)
print(a)

In [ ]:
np.sort(a,axis=0)

In [ ]:
# here axis=0 represent column , column based sorting


# example of linear algebra
- solve()
- det()
- inv()


In [ ]:
# consider the following linear equation:-
#2x+3y=6 -->1
#6x+4y=3 -->2
# find the value of x and y
a=np.array([[2,3],[6,4]])  
b=np.array([6,3])
sol=np.linalg.solve(a,b)
print(sol)


In [ ]:
#x+y+z=6
#2x+3y+9z=16
#2x-4y-9z=20
a=np.array([[1,1,1],[2,3,9],[2,-4,-9]])
b=np.array([6,16,20])
sol=np.linalg.solve(a,b)
print(sol)
print("val of x=",sol[0])
print("val of y=",sol[1])
print("val of z=",sol[2])

In [ ]:
# find det of given matrix
a=-np.array([[1,2],[3,4]])
detA=np.linalg.det(a)
print(detA)


In [ ]:
# find det of given matrix
a=-np.array([[1,2,3],[4,5,6],[7,8,2]])
detA=np.linalg.det(a)
print(detA)


In [ ]:
# inverse of given matrix
a=np.array([[1,2],[3,4]])
invA=np.linalg.inv(a)
print(invA)

- develop by wes mc kinney - package/module/
- pip install pandas
- import pandas as pd 
- print(pd.__version___)

- pip show pandas
- pip list
- in pandas data is organise in 1 . series 2. datafrane 3. panel


# Pandas
- why do we need panadas ?
- it is fast , flexible and powerful data mining library , pandas is the most crucial module for applying data science using python 

- *********************
- Advantage of pandas:-
    - easy import and export into tabular formaty data structures like dataframe
    - routing( function and method ) for manipulation
    - easy handling of missing data
    - data set cleaning , merging and joining.
    - reshaping data set .
    column can be inserted ,deleted and updated from dataframe and higher dimension object.
    - time series based data manipulation and analysis API
    - group by functionality to perform split apply combine operation.
    - well integrated with other library  like numpy and and matplotlib.
    - data produce by pandas are often used as data visualisation.
    

In [ ]:
"""  
  data structure used in pandas:-
  1. series
  2. data frame
  3. panel
"""

# series
    - it is 1D array , it is capable of storing same type  + diffrent type and all types and internally treated as same type as object.
    - all values in series contain by default indices (row indices {start from 0 to n-1 here n represent number of values})
    - programtically , we can give programmer defined indices for values of series instead of default indices.
    - series object are "mutable" objects.
    - series data can be accessed either w.r.t indices (axis) or  programmer defined indices called (label).
    - on series object we can perform indexing and slicing operations.

******************************
- number of approaches to create an object of series:-
    - varname = pandas.Series(object,index,dtype)



In [ ]:
import pandas as pd
print(pd.__version__)

In [ ]:
# creating an object of series
# syntax varname = pandas.Series(object,index,dtype

In [ ]:
a=100
print(a,type(a))

In [ ]:
s=pd.Series(a)
print(s,type(s))

In [ ]:
s=pd.Series(10.15)
print(s,type(s))

In [ ]:
fo=12.34
s=pd.Series(fo)
print(s,type(s))

In [ ]:
fo=False
s=pd.Series(fo)
print(s,type(s))

In [ ]:
fo=12.34+5j
s=pd.Series(fo)
print(s,type(s))

In [ ]:
a=100
s=pd.Series(a,dtype=float)
print(s,type(s))

In [ ]:
s1="python"
s=pd.Series(s1)
print(s,type(s1))

In [ ]:
# creating a series object by using range
r=range(6)
s=pd.Series(r)
print(s,type(s))

In [ ]:
# creating a series object by using range with default indices
r=range(6)
s=pd.Series(r,index=[1,2,3,4,5,6])
print(s,type(s))

In [ ]:
# creating a series object by using range with default indices
r=range(6)
s=pd.Series(r,index=["id1", "id2", "id3", "id4","id5","id6"])
print(s,type(s))

In [ ]:
s["id1"]

In [ ]:
s["id5"]

In [ ]:
# keyerror - because no default indices present when we give programmer defined int indices.

In [ ]:
# creating a series of object by using list/tuple with default indices
lst=[10,20,30,40,50,60]
s=pd.Series(lst)
print(s,type(s))

In [ ]:
# creating a series of object by using list/tuple with default indices
lst=[10,20,30,40,50,60]
s=pd.Series(lst,index=[1,2,3,4,5,6],dtype=float)
print(s,type(s))

In [ ]:
# creating a series of object by using list/tuple with default indices
lst=[10,20,30,40,50,60]
s=pd.Series(lst,index=[int(x) for x in range(1,7)],dtype=float)
print(s,type(s))

In [ ]:
# creating a series of object by using list/tuple with default indices
lst=[10,20,30,40,50,60]
s=pd.Series(lst,index=["id" + str(int(x)) for x in range(1,7)],dtype=float)
print(s,type(s))

In [ ]:
# creating a series of object by using list/tuple with default indices
tpl=(10,20,30,40,50,60)
s=pd.Series(lst,index=["id" + str(int(x)) for x in range(1,7)],dtype=float)
print(s,type(s))

In [ ]:
# creating a series of object by using set with default indices
# set does not maintain insertion order
s1={10,20,30,40,50,60}
print(s1,type(s1))


In [ ]:
# creating a series of object by using set with default indices
# set does not maintain insertion order
s1={10,20,30,40,50,60}
print(s1,type(s1))
print(50*"*")
s=pd.Series(s1)
print(s,type(s))

In [ ]:
# in pandas set is not possible if you want then convert it into list/tuple

In [ ]:
# creating a series of object by using dict  
d1={10:"python",20:"django",30:"ml",40:"dl"}
print(d1,type(d1))

In [ ]:
s=pd.Series(d1)
print(s,type(s))

In [ ]:
s[10]

In [ ]:
s[20]

In [ ]:
s[10:30]

In [ ]:
#empty series is created 

In [ ]:
d={"crs1":["python","django","data science"],"crs2":["java","hibernet","spring"]}

In [ ]:
for key,value in d.items():
    print("{}-->{}".format(key,value))

In [ ]:
s=pd.Series(d)
print(s)

In [ ]:
s["crs1"]

In [ ]:
s[1]

In [ ]:
import numpy as np
a=np.array((100,200,300,400,500))
print(a)
print(20*"-")
s=pd.Series(a)
print(s)

In [ ]:
a=np.array((100,200,300,400,500))
print(a)
s=pd.Series(a,index=["id" +str(int(x)) for x in range(1,len(a)+1)],dtype=float)
print(s)

# set and get data to / from series object

In [ ]:
names= pd.Series(["mark","sundar","musk","rossum","travis"],index=["a","b","c","d","e"])
print(names)

In [ ]:
ser=pd.Series(range(1,20,3),index=[x for x in "abcdefg"])
print(ser)

In [ ]:
ser=np.arange(10,15)
serobj=pd.Series(data=ser*5,index=ser)
print(serobj)

In [ ]:
# loc and iloc
# loc --> location
# iloc --> index location
# loc is used to access the data using the index value
# iloc is used to access the data using the index position



In [ ]:
names.iloc[0:4]

In [ ]:
#syntax:-
#series obj.iloc[begin:end:step]


In [ ]:
names.loc["a":"d"]

In [ ]:
names.loc[::-1]

In [ ]:
names.iloc["a":"d"]

In [ ]:
"""  
loc[]--> default indices are possible+ programmer define indices are also possible

iloc[]--> default indices possible+ programmer define indices are not possible.

"""

In [ ]:
names=pd.Series(["mark","rita","vickey","justin","john","michel"])
print(names)

In [ ]:
names[0]="sujata"
print(names)

In [ ]:
# changed 2 names at once 
names[1:3]=["sangeeta","pragati"]
print(names)

In [ ]:
names[6]="dori"
print(names)

In [ ]:
names[7]="deep"
print(names)


In [ ]:
del names[7]
print(names)

# attribute of Series object
    - name of pandas series object
    - get all values of series as a list
    - get count of number of element in series
    - check if series is empty or not
    - get first n element of pandas series
    - get last n element of pandas series
    - get the count of non NaN value
    --------------------------------
    # add and remove series element
    - adding / merging series together
    - subtracting two series
    - deleting element from series
    - get sum of all values in the series
    - get the max values in the series

In [ ]:
import pandas as pd
names = pd.Series(["dori","itty","dhurvi","geet"],index=["a","b","c","d"])
print(names)

In [ ]:
print(names.values)

In [ ]:
lst=list(names.values)
print(lst)

In [ ]:
# missing number in pandas are represented by NaN


In [ ]:
a=np.array([10,20,None,30,40,True])
print(a)

In [ ]:
s=pd.Series(a)
print(s)

In [ ]:
print(s.count())

In [ ]:
s1=pd.Series(["dori","itty","dhurvi","geet",10,20,30,False,None],name="students")
print(s1)

In [ ]:
# get the first n element in pandas series --- we use head() of series object.


In [ ]:
import pandas as pd
s1=pd.Series(range(10,100,5))
print(s1)

In [ ]:
print(s1.head())

In [ ]:
print(len(s1))

In [ ]:
#get first three elements in pandas series
print(s1.head(3))

In [ ]:
# to get last 10 value we use tail() of series object
print(s1.tail())

In [ ]:
print(s1.tail(10))

In [ ]:
# another method to get first 5
s1[0:5]

In [ ]:
# another method to get last 5
s1[-5:]

In [ ]:
# add and remove series element
# to add the element of one series object to another we use a function add()

#syntax: varname=serobj1.add(serobj2,fill_value=None)

In [ ]:
# to add a series element
s1=pd.Series([100,200,300,400,500],index=["a","b","c","d","e"])
s2=pd.Series([10,20,30,40],index=["a","b","g","e"])
res=s1.add(s2)
print(res)

In [ ]:
# fill NaN with other value 
s1=pd.Series([100,200,300,400,500],index=["a","b","c","d","e"])
s2=pd.Series([10,20,30,40],index=["a","b","g","e"])
res=s1.add(s2,fill_value=0)
print(res)

In [ ]:
# to subtract a series element
s1=pd.Series([100,200,300,400,500],index=["a","b","c","d","e"])
s2=pd.Series([10,20,30,40],index=["a","b","g","e"])
res=s1.subtract(s2)
print(res)

In [ ]:
# to subtract a series element
s1=pd.Series([100,200,300,400,500],index=["a","b","c","d","e"])
s2=pd.Series([10,20,30,40],index=["a","b","g","e"])
res=s1.subtract(s2,fill_value=0)
print(res)

In [ ]:
# to multiply a series element
s1=pd.Series([100,200,300,400,500],index=["a","b","c","d","e"])
s2=pd.Series([10,20,30,40],index=["a","b","g","e"])
res=s1.multiply(s2)
print(res)

In [ ]:
# to delete c
res=s1.drop("c")
print(res)

In [ ]:
print(s1)

In [ ]:
# note s1 is not modified

In [ ]:
# some statistics function for data science:-
""" 
1. sum()
2. count()
3. mean()
4. median()
5. variances()
6. std()
7. max()
8. min()
9. mode()
"""

In [ ]:
s=pd.Series([10,20,13,4,0,12])
print(s)

In [ ]:
print("sum of elements",s.sum())

In [ ]:
import pandas as pd
import numpy as np
s=pd.Series([10,20,13,4,0,12,np.nan,None])
print(s)

In [ ]:
import pandas as pd
import numpy as np
s=pd.Series([12,34,15,8,22,10,8,-4])
print(s)

In [ ]:
print(s.sort_values(ascending=False))

In [ ]:
print(s.sort_values(ascending=False,inplace=True))
print(s)

In [ ]:
print(s.head(2))

In [ ]:
print(s[0:2])

In [ ]:
print(s.tail(3))

In [ ]:
s=pd.Series([12,34,15,8,22,10,8,-4])
print(s)

In [ ]:
s=pd.Series([12,34,15,8,22,10,8,-4])
print(s)

In [ ]:
print(s.nlargest(3))

In [ ]:
print(s.nsmallest(3))

In [ ]:
s=pd.Series([12,34,15,8,22,10,8])
print(s)

In [ ]:
print("sum=",s.sum())
print("product=",s.product())
print("mean=",s.mean())

In [ ]:
# new method to get all at once 
s=pd.Series([12,34,15,8,22,10,8])
s.agg(["sum","prod","mean","median"])

In [ ]:
# working with missing dependencies values

In [ ]:
# to work with csv files

# pd.read_csv("absolute path of csv file")

# pandas.read_csv("absolute path of pandas")

# this are separated by double slash

# by default , the pandas read_csv() will be imported as dataframe

# if we want data to be imported into series instead of dataframe we provide additional argument use cols and squeeze , the squeeze=true will convert a dataframe of one column into series.


In [ ]:
names=["Rossum","traVis","itTy","DhurVi","dEEp"]
lst=[name.lower() for name in names]
print(lst)

In [ ]:
names=["Rossum","traVis","itTy","DhurVi","dEEp"]
lst=[name.upper() for name in names]
print(lst)

In [ ]:
names=["Rossum","traVis","itTy","DhurVi","dEEp"]
lst=[len(str(name)) for name in names]
print(lst)

In [ ]:
names=["Rossum","traVis","itTy","DhurVi","dEEp"]
lst={str(name):len(str(name)) for name in names}
print(lst)

In [ ]:
names=["Rossum","traVis","itTy","DhurVi","dEEp"]
lst={str(name.lower()):len(str(name)) for name in names}
print(lst)

In [ ]:
names=["Rossum","traVis","itTy","DhurVi","dEEp"]
s=pd.Series(names)
uperCaseNames=pd.Series([str(name).upper() for name in s]).sort_values()
print(uperCaseNames)

In [ ]:
names=["Rossum","traVis","itTy","DhurVi","dEEp"]
s=pd.Series(names)
uperCaseNames=pd.Series([str(name).lower() for name in s]).sort_values()
print(uperCaseNames)

# data frame
- dataframe is one of the class and whose object allows us to store the data in tabular format or 2d format and we can perform data analysis.
- data frame is one of the 2 dimension label array capable of storing similar type or diffrent type or both type in single object.
- even we store multiple value of diffrent type internally those value are treated as object .
- dataframe=data set + indices + columns 
- data set represent the collection of values and they may contain same type or diffrent type
- indices represent row indices , whose indices by default start from 0 to N-1, here N is the number of rows.
- the default rows indices can be assigned by programmer accordinng to programmer choice.
- column represent column indices , whose default start from 0 to M-1 here M is the number of columns.
- an objectof dataframe is "Mutable"  we can perform many operation at same address.

In [ ]:
# number of approaches to create an object of dataframe:-

"""  

syntax:- 

varname= pandas.DataFrame(object,index,columns,dtype)

"""

In [ ]:
a=10
print(a,type(a))

In [ ]:
a=10

df=pd.DataFrame(a)
print(df)

In [ ]:
# note :
""" 
- therefore above is ValueError
-for single value there is no meaning for creating dataset. 
-single value cannot be created as dimension
"""

In [ ]:
a=10.12

df=pd.DataFrame(a)
print(df)

In [ ]:
a="python"

df=pd.DataFrame(a)
print(df)

In [ ]:
# ValueError


In [ ]:
a=1000
# here a is a int single value
# convert it into list 
lst=list([a])
print(lst)

In [ ]:
# convert it into dataframe
a=1000
# here a is a int single value
# convert it into list 
lst=list([a])
print(lst)
df=pd.DataFrame(lst)
print(df)

In [ ]:
s="python"
lst=list(s)
print(lst)
df=pd.DataFrame(lst)
print(df)

In [ ]:
# convert the lsit into dataframe
lst =[100,"rossum","travis",32.22,"hunter"]
print(lst)
df=pd.DataFrame(lst)
print(df)
print(type(df))

In [ ]:
# convert the lsit into dataframe
lst =[100,"rossum","travis",32.22,"hunter",[10,20,30]]
print(lst)
df=pd.DataFrame(lst)
print(df)
print(type(df))

In [ ]:
lst=[[10,20,30],["rossum","travis","hunter"]]
print(lst)
print(50*"-")
df=pd.DataFrame(lst,columns=["id","name","famous"])
print(df)

In [ ]:
# convert list value into dataframe

lst=[[10,"rs"],[20,"ts"],[30,"hs"]]
print(lst)
print(50*"-")
df=pd.DataFrame(lst,index=["row1","row2","row3"],columns=["id","name"])
print(df)


In [ ]:
# convert tuple value into dataframe

lst=([10,"rs"],[20,"ts"],[30,"hs"])
print(lst)
print(50*"-")
df=pd.DataFrame(lst,index=["row1","row2","row3"],columns=["id","name"])
print(df)

In [ ]:
# convert tuple value into dataframe

lst=((10,"rs"),(20,"ts"),(30,"hs"))
print(lst)
print(50*"-")
df=pd.DataFrame(lst,index=["row1","row2","row3"],columns=["id","name"])
print(df)

In [ ]:
# set
st={10,20,30,40,50}
print(st)
df=pd.DataFrame(st)
print(df)

In [ ]:
#dictionary
d={100:"rs",200:"ts",300:"hs"}
print(d)

In [ ]:
d={"sub1":["pyhton","javascript","datascience"],"sub2":["html","css","react"],"sub3":["oracle","sql","mongodb"]}

print(d,type(d))

In [ ]:
for key, value in d.items():
    print(key,"->",value)

In [ ]:
d={"sub1":["pyhton","javascript","datascience"],"sub2":["html","css","react"],"sub3":["oracle","sql","mongodb"]}

print(d,type(d))

df=pd.DataFrame(d)
print(df,type(df))

In [ ]:
d={"sub1":["pyhton","javascript","datascience"],"sub2":["html","css","react"],"sub3":["oracle","sql","mongodb"]}

print(d,type(d))

df=pd.DataFrame(d,index=["level1","level2","level3"])
print(df,type(df))

In [ ]:
# creating dataframe object by using dict
d={10:"python",20:"java",30:"c",40:"c++"}
print(d)
print(50*"-")
df=pd.DataFrame(d)
print(df,type(df))

In [ ]:
# you will get the value error 
# since you are passing the single value in dict
# for removing error you need to provide the index

In [ ]:
# key:value
# key become columns
# value become rows

In [ ]:
# creating dataframe object by using dict
d={10:"python",20:"java",30:"c",40:"c++"}
print(d)
print(50*"-")
df=pd.DataFrame(d,index=["course"])
print(df,type(df))

In [ ]:
# creating nd array object
d={"sub1":["pyhton","javascript","datascience"],"sub2":["html","css","react"],"sub3":["oracle","sql","mongodb"]}

print(d,type(d))

a=np.array(d)
print(a,type(a))
print(a.ndim)

In [ ]:
# creating dataframe obejct using dict
d={"sub1":["pyhton","javascript","datascience"],"sub2":["html","css","react"],"sub3":["oracle","sql","mongodb"]}
a=np.array(d)
print(a,type(a))
print(a.ndim)
df=pd.DataFrame(a)
print(df,type(df))

In [ ]:
# you will get the value error 
# to make txt file to csv file ["fileName.csv"] it must be contain with in the double quoted string

In [ ]:
# create an object of dataframe by using csv file
#syntax
""" 
dataframeObj=pandas.read_csv("absolute path of csv with double slash")
"""
df=pd.read_csv("D:\\clone\\DataAnalyst_DPK\\files\\student.csv")
print(df)

In [ ]:
df.set_index("sno")

# Attributes of dataframe objects:-
1. index
2. columns
3. dtype
4. shape
5. size
6. ndim
7. empty
8. T
9. values
10. axis

In [ ]:
# creating a 2d dictionary
import numpy as np
import pandas as pd
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [25, 30, 28, 35],
    'City': ['New York', 'Paris', 'London', 'Tokyo']
}
df=pd.DataFrame(data)
print(df)

In [ ]:
# creating a 2d dictionary
dict={"student":["arvind","aryan","travis","rossum"],"marks":[85,78,80,90],"sports":["cricket","tennis","volleyball","badminton"]}

# creating it into dataframe


In [ ]:
df=pd.DataFrame(dict)
print(df)

In [ ]:
print(df.index)

In [ ]:
# column attribute 
print(df.columns)

In [ ]:
print(df.axes)

In [ ]:
dict={"sales":{"name":"rossum","age":67,"gender":"male"},"marketting":{"name":"travis","age":65,"gender":"female"}}
df=pd.DataFrame(dict)
print(df)

In [ ]:
print(df.axes)

In [ ]:
# axes will show you both x-axis and y-axis

In [ ]:
print(df.T)

# category data types :~

In [ ]:
import pandas as pd
s=pd.Series(["python","java","python","c++","java","dsc","dsc","python","java"])
print(s,type(s))

In [ ]:
s=pd.Series(["python","java","python","c++","java","dsc","dsc","python","java"],dtype="category")
print(s,type(s))

In [ ]:
# dtype="category" will group the dataset

# Accessing the data from dataframe:-
- dataframeobj[index]
- dataframeObj[StartIndex:EndIndex]
- dataframeObj[StartIndex:]
- dataframeObj[:EndIndex]
- dataframeObj[StartIndex:EndIndex:stepIndex]
- dataframeObj.head()
- dataframeObj.tail()
- dataframeObj.iterrows()
- dataframeObj.head()
- dataframeObj.describe()
- dataframeObj.at()
- dataframeObj.iat()
- dataframeObj.iloc()
- dataframeObj.loc()


In [ ]:
import pandas as pd
import numpy as np


In [ ]:
# get the data from student.csv into dataframe
df= pd.read_csv("D:\\clone\\DataAnalyst_DPK\\files\\student-dataset.csv")
print("="*50)
print(df)
print("="*50)

In [ ]:
# column attribute 
print(df.columns)

In [ ]:
df.head()
# obtain the first five records / rows from datatframe

In [ ]:
df.tail()
# obtain the last five records / rows from datatframe

In [ ]:
df.head(3)
# to get the first three record

In [ ]:
df.describe()
# this function give the statistical summary of the dataframe

In [ ]:
df.shape
# it will give you the row and column count of the dataframe

In [ ]:
# obtain the column
df.columns

In [ ]:
# obtain the row
df.shape[0]

In [ ]:
# obtain the column
df.shape[1]

In [ ]:
df.index

In [ ]:
df1=df[4:10:2]
df1

In [ ]:
# to get the center of the dataframe
df[len(df)//2:len(df)//2+1]

In [ ]:
# extract the data based on column name


In [ ]:
# get the names
df['name']

In [ ]:
seriesObj=df['name']

In [ ]:
print(seriesObj)

In [ ]:
df[['name','age']]

In [ ]:
df['nationality']

# get the column of desire
- syntax:-
    dataFrameObj[['colName1','colName2',...'colName-n']][startIndex:EndIndex:StepIndex]

In [ ]:
for record in df.iterrows():
    print(record)

In [ ]:
df.info()

In [ ]:
# pandas --> loc and iloc

"""  
loc and iloc uses square bracket
-> present in both in series and  dataframes object.
-> 
-----------------------
=>loc[] is used for slicing the data either on the basis row index and column index.
=> loc[] always take row index and column names only (never take column index)
syntax: dataFrameObj.loc[]
dataFrameObj.loc[row_number]
dataFrameObj.loc[row_number,[col name,..]]
dataFrameObj.loc[start:stop:step,[col name]]


"""

In [ ]:
# info() - it is a pre defined function in series and dataframe object and the gives the following information

In [ ]:
import pandas as pd
import numpy as np
# get the data from student.csv into dataframe
df= pd.read_csv("D:\\clone\\DataAnalyst_DPK\\files\\student-dataset.csv")
print("="*50)
print(df)
print("="*50)

In [ ]:
df.info()

In [ ]:
df.loc[3,["name","nationality"]]

In [ ]:
#syntax
#dataFrameObj.loc[row_number,[colName1,colName2..]]

In [ ]:
df.loc[3:7]

In [ ]:
#iloc[]
"""  
=>iloc[] is used for slicing the data either on the basis rows(Index) and column(columns)
=>iloc[] always takes row indeces and never takes column indecs
=>
"""

In [ ]:
#syntax:
#dataFrameObj.iloc[row_number,[ColNumber1,colNumber2,..]]

#dataFrameObj.iloc[rowStart:rowStop:rowStep,colStart:colStop:colStep]

In [ ]:
#get the 7th records
df1=df.iloc[7]
df1

In [ ]:
# get the first name
y=df1["name"][:7]
y


In [ ]:
df.iloc[3:10,[1,3]]["name"]

In [ ]:
#lec 30

Adding new column name to data frame :-

In [ ]:
# how to add a new column 
# eno,name,sal,comm,compname
# 100,rossum,34.56,10.00,psf

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# get the data
df=pd.read_csv("D:\\clone\\DataAnalyst_DPK\\files\\student.csv")
print(df)

In [ ]:
# add a new column -total salary
# syntax for adding a new column name
# dataFrameObj[new column name]=value/expression

df["totsal"]=100


In [ ]:
print(df)

In [ ]:
# get the data
df=pd.read_csv("D:\\clone\\DataAnalyst_DPK\\files\\emp.csv")
print(df)

In [ ]:
# adding a new column to a data frame :-
# print the total salary
df["totalSal"]=df["sal"]+df["comm"]
print(df)

In [ ]:
# export or modify the emp.csv with modified data 
# to do this we use 
# dataFrameObj.to_csv("absolute_path")

In [ ]:
df.to_csv("D:\\clone\\DataAnalyst_DPK\\files\\Modifiedemp.csv")
print(df)

In [ ]:
# another example
d={"a":[10,20,30,40],"b":[1,2,3,4],"c":[1.1,2.2,3.3,4.4]}
print(d,type(d))

In [ ]:
for key,val in d.items():
    print(key,"-->",val)

In [ ]:
# convert dict object into dataframe
df=pd.DataFrame(d)
print(df)

In [ ]:
# add a new column and add the value of a,b,c in it
df["sum"]=df["a"]+df["b"]+df["c"]
print(df)

In [ ]:
df.to_csv("D:\\clone\\DataAnalyst_DPK\\files\\dictSum.csv")

In [ ]:
# calculate the %
df["percentage"]=(df["sum"]/100)*100
print(df)

In [ ]:
# create a student data table
studentData={"sno":[1,2,3,4],"name":["dhurvi","deepak","itty","rossum"],"eng":[98,95,95,99],"math":[100,96,96,98],"science":[99,92,94,93]}

# convert dict object into dataframe
df=pd.DataFrame(studentData)
print(df)
print("-"*50)
df.to_csv("D:\\clone\\DataAnalyst_DPK\\files\\studentData.csv")
print("-"*50)
print(df)

In [ ]:
# cal the total marks
df["total"]=df["eng"]+df["math"]+df["science"]
print(df)

In [ ]:
# full marks subject wise
df["fullMarks"]=300
print(df)

In [ ]:
# cal the %
df["percentage"]=round((df["total"]/df["fullMarks"])*100,2)
print(df)

In [ ]:
# give the grade acording to %
# filtering the data


In [ ]:
df.to_csv("D:\\clone\\DataAnalyst_DPK\\files\\ModifiedstudentData.csv")

In [ ]:
print(df)

# Filtering the data in pandas

In [ ]:
# example on filtering the data

In [ ]:
# get the data
df=pd.read_csv("D:\\clone\\DataAnalyst_DPK\\files\\emp.csv")
print(df)

In [ ]:
df["sal"]>5000

In [ ]:
# it will give the boolean array

In [ ]:
df[df["sal"]>5000]


In [ ]:
# get the names of those employee whose salary range between 5000 and 9000
(df["sal"]>=5000) & (df["sal"]<9000)

In [ ]:
# get the data
df[(df["sal"]>=5000) & (df["sal"]<9000)]

In [ ]:
# print only name and sal
df[(df["sal"]>=5000) & (df["sal"]<9000)][["name","sal"]]

In [ ]:
# get the emplyee name who only work in numpy
df["com"]=="numpy"

In [ ]:
df[df["com"]=="numpy"][["name","sal"]]

In [ ]:
#total sal paid to all the employee
df["sal"].sum()

In [ ]:
# find the emp who are working in numpy and react
(df["name"]=="react")| (df["name"]=="numpy")

In [ ]:
df[(df["com"]=="react")| (df["com"]=="numpy")][["name","sal","com"]]

In [ ]:
for name in df[(df["com"]=="react")| (df["com"]=="numpy")]["name"]:
    print(name)

In [ ]:
# get he company name
df["com"]

In [ ]:
for cname in df["com"]:
    print(cname)

In [ ]:
for cname in df["com"]:
    if cname in ["numpy","javascript"]:
        print(df)

In [ ]:
# another method
x=dict(df[["name","com"]])
print(x)

In [ ]:
# get the data via loc
df.loc[(df["com"]=="numpy")| (df["com"]=="javascript")]["name"]

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# get the data
df=pd.read_csv("D:\\clone\\DataAnalyst_DPK\\files\\Modifiedemp.csv")
print(df)

# Data filtering an Updation on DataFrame object

In [ ]:
# conditional based updation

In [ ]:
df.columns

In [ ]:
df.loc[df["com"]=="psf"]

In [ ]:
#to get only names
df.loc[df["com"]=="psf"]["name"]

In [ ]:
# count the number of people
len(df.loc[df["com"]=="psf"]["name"])

In [ ]:
# update "psf" as "python software foundation"
df.loc[df["com"]=="psf",["com"]]="python software foundation"
print(df)

In [ ]:
# pick the person who have commision 80

df.loc[(df["name"]=="rohit") & (df["comm"]==80)]

In [ ]:
#syntax
# dataframeObj.loc[(compound condition),["col name","colname2",..]]=expression

In [ ]:
# give the grading 
# 100-75 distinction
# 75-65 first
# 65-55 second
# <60 third

In [ ]:
# get the data
df=pd.read_csv("D:\\clone\\DataAnalyst_DPK\\files\\student-dataset.csv")
print(df)

In [ ]:
df.columns

In [ ]:
df["english.grade"]

In [ ]:
# 1.5 lec31
# df.loc[((df["percent"]>=60) & (df["percent"]<65)),["grade"]]="second"
# print(df)

- pandas removing column name fom data frame 
- dataframe.drop(columns="col name")
- dataframe.drop(columns=["col1","col2...])
- dataframe.drop(columns=DataFrame.Obj.columns[colNumber])

In [ ]:
# removing the columns name from data frame:-
import pandas as pd
# get the data from student.csv
df=pd.read_csv("D:\\clone\\DataAnalyst_DPK\\files\\ModifiedstudentData.csv")
print(df)


In [ ]:
# to delete one columns completely
# remove the sno
# syntax : dataframe.drop(columns-"col-name")

In [ ]:
print(df.drop(columns="sno"))


In [ ]:
# to make delete permanet use inplace=true

In [ ]:
# to delete two columns at once
# syntax :- dataframe.drop(columns=["col1","col2",..])
# eg:-
print(df.drop(columns=["eng","math"]))

In [ ]:
# to make it permanent inplace=true
# print(df.drop(columns=["eng","math"],inplace=True))

In [ ]:
# removing the columns names from dataframe based on columns number
# syntax:- dataframe.drop(columns-dataframeobj.columns["col1","col2"..])
# df.drop(columns=df.columns[[2,4]],inplace=true)

In [ ]:
# removing the ROWS from the data frame
# to delete one row

In [ ]:
df=pd.read_csv("D:\\clone\\DataAnalyst_DPK\\files\\ModifiedstudentData.csv")
print(df)

In [ ]:
#suntax: - dataframeObj.drop(label=index,value,axis=0)
# axis=0 means row and axis=1 means column
# df.drop(labelss=[index1,index2,...,axis=0,inplace=True)


In [ ]:
# removing the records from database/ row
# syntax: - dataframeObj.drop(label=index,value,axis=0)

In [ ]:
print(df.drop(labels=[1,3],axis=0))



In [ ]:
# apply for loop
# df.drop(labels=[int(y) for y in range(7,12)],axis=0,inplace=True))

In [ ]:
# remove the index based on user choice

In [ ]:
df.index

In [ ]:

# syntax: dataframeObj.drop(df.index[randomIndex1,randomIndex2,...],axis=0,inplace=True)

# df.drop(df.index[[1,3,14]])

In [ ]:
# sorting the data from dataframe

In [ ]:
# syntax: dataframeObj.sort_values(by="colname",ascending=True/False)

In [ ]:
df.sort_values(["name"],ascending=True,inplace=True)
print(df)

In [ ]:
# reverse the order
df.sort_values(["name"][::-1],inplace=True)
print(df)

In [ ]:
print(df)

In [ ]:
df.sort_values(["name"],ascending=False,inplace=True)
print(df)

In [ ]:
# get the math result
df.sort_values(["math"],ascending=True,inplace=True)
print(df)

In [ ]:
# get the highest secured max marks and names
df.tail(2)[["name","math"]]

In [ ]:
# or
df[-2:-1]

In [ ]:
df[-2:-1][["name","math"]]

In [ ]:
df[-2:][["name","math"]][::-1]

In [ ]:
# find the second least highest marks with name

In [ ]:
df[1:2][["name","math"]]

In [ ]:
# knowing the duplicate data in data frame
# syntax: dataframeObj.duplicated()--> gives the boolean result
# syntax: dataframeObj.duplicated(subset=["col1","col2",..],keep="first/last/all")

In [ ]:
# removing duplicated data 
# syntax: dataframeObj.drop_duplicates(inplace=True)

In [ ]:
df.duplicated()

In [ ]:
# remove dulpicate
df.drop_duplicates(inplace=True)
print(df)

In [ ]:
# find the name of the student whose name start with "d"

In [ ]:
df.columns

In [ ]:
df["name"]

In [ ]:
# or 
df.loc[::,["name"]]

In [ ]:
df.loc[df["name"].str.startswith("d")]

In [ ]:
# or 
for sname in df["name"]:
    
    if (sname.startswith("d") or sname.startswith("D")):
        print(sname,type(sname))
      

In [ ]:
#----lec32---completed

# Pandas - groupby()

# syntax:-
- DataFrameObj.groupby("colName")

In [ ]:
# varName=DataFrameObj.groupby("colName")

In [ ]:
# example on groupby

In [ ]:
# get the people data with state wise
#grp_people=df.groupby("state")

In [ ]:
# using the for loop
# for gname,ginfo in grp_people:
#     print(gname)
#     print("\t{0} people".format(len(ginfo))) 
#     print(ginfo)

In [ ]:
# obtain first record of each group
#grp_people=df.groupby("state").first()

In [ ]:
# get the last record of each gropu
#grp_people=df.groupby("state").last()

In [ ]:
# get the third record of each group
#grp_people=df.groupby("state").nth(2)

In [ ]:
# get the count of each group exclusively
#grp_people=df.groupby("state").count()
# get the count of each group including NaN values
#grp_people=df.groupby("state").size()

In [ ]:
# name of people living that state
#grp_people=df.groupby("state")["name"]
#grp_people=df.groupby("state")["name"].count()

In [ ]:
d={"id":[10,20,30,40,50,60,70],"name":["dhurvi","itty","deepak","dori","lovely","pragati","shayam"],"city":["delhi","delhi","mumbai","mumbai","pune","pune","pune"],"state":["delhi","delhi","maharashtra","maharashtra","maharashtra","maharashtra","maharashtra"]}

df=pd.DataFrame(d)
print(df)

df.to_csv("D:\\clone\\DataAnalyst_DPK\\files\\cityPeople.csv")

In [ ]:
# get the people data with state wise
grp_people=df.groupby("state")
print(grp_people.groups)

In [ ]:
grp_people=df.groupby("state")
print(grp_people.groups)

In [ ]:
grp_people=df.groupby("state").first()
print(grp_people)

In [ ]:
grp_people=df.groupby("state")["name"]
print(grp_people)

In [ ]:
df.groupby("state")["name"].size()

In [ ]:
import pandas as pd
d={"id":[10,20,30,40,50,60,70,80,90,100],"name":["dhurvi","itty","deepak","dori","lovely","pragati","shayam","aadi","bablu","anuj"],"city":["delhi","delhi","mumbai","mumbai","pune","pune","pune","goa","kolkatta","hydrabad"],"state":["delhi","delhi","maharashtra","maharashtra","maharashtra","maharashtra","maharashtra","goa","kolkatta","hydrabad"],"age":[20,21,22,23,24,25,26,27,28,29],"experience":[1,2,3,4,5,6,7,8,9,10],"salary":[10000,20000,30000,40000,50000,60000,70000,80000,90000,100000]}

df=pd.DataFrame(d)
print(df)

df.to_csv("D:\\clone\\DataAnalyst_DPK\\files\\studentLife.csv")

    id     name      city        state  age  experience  salary
0   10   dhurvi     delhi        delhi   20           1   10000
1   20     itty     delhi        delhi   21           2   20000
2   30   deepak    mumbai  maharashtra   22           3   30000
3   40     dori    mumbai  maharashtra   23           4   40000
4   50   lovely      pune  maharashtra   24           5   50000
5   60  pragati      pune  maharashtra   25           6   60000
6   70   shayam      pune  maharashtra   26           7   70000
7   80     aadi       goa          goa   27           8   80000
8   90    bablu  kolkatta     kolkatta   28           9   90000
9  100     anuj  hydrabad     hydrabad   29          10  100000


In [ ]:
# create list in list from above data frame
lst=[[10,"dhurvi","delhi","delhi",20,1,10000],
[20,"itty","delhi","delhi",21,2,20000],
[30,"deepak","mumbai","maharashtra",22,3,30000],
[40,"dori","mumbai","maharashtra",23,4,40000]]


In [ ]:
df=pd.DataFrame(lst,columns=["id","name","city","state","age","experience","salary"])
print(df)

   id    name    city        state  age  experience  salary
0  10  dhurvi   delhi        delhi   20           1   10000
1  20    itty   delhi        delhi   21           2   20000
2  30  deepak  mumbai  maharashtra   22           3   30000
3  40    dori  mumbai  maharashtra   23           4   40000


In [ ]:
# get the mean age column value in each group
values=df.groupby("city").agg({"age":"mean","salary":"sum"})
print(values)

         age  salary
city                
delhi   20.5   30000
mumbai  22.5   70000


In [ ]:
values2=df.groupby("city")["age"].agg(["size","sum","mean","median","std","var"])
print(values2)

        size  sum  mean  median       std  var
city                                          
delhi      2   41  20.5    20.5  0.707107  0.5
mumbai     2   45  22.5    22.5  0.707107  0.5


In [ ]:
# case study 1
d={"cid":[10,20,30,40,50,60,70,80,90,100],"name":["dhurvi","itty","deepak","dori","lovely","pragati","shayam","aadi","bablu","anuj"],"city":["TS","AP","MUM","MUM","AP","TS","TS","AP","TS","MUM"],"expert":["python","python","java","java","c","c","c","python","python","java"],"age":[88,78,79,23,22,24,22,23,22,23],}

df=pd.DataFrame(d)
print(df)

df.to_csv("D:\\clone\\DataAnalyst_DPK\\files\\citizen.csv")

   cid     name city  expert  age
0   10   dhurvi   TS  python   88
1   20     itty   AP  python   78
2   30   deepak  MUM    java   79
3   40     dori  MUM    java   23
4   50   lovely   AP       c   22
5   60  pragati   TS       c   24
6   70   shayam   TS       c   22
7   80     aadi   AP  python   23
8   90    bablu   TS  python   22
9  100     anuj  MUM    java   23


In [ ]:
# analysis on the data frame
# Q. find the name of the people who are present in citizen file  
# get first 5 people name
# find all the people names of bottom five
# find names ,city and their expertism of citizen
# find the name of the people who are living in "TS"
# find name , ages of people ho are living in either in ap or in ts
# find the name of the city where python expert are wroking.
# find the names of the people whose name start with "a"
# find the average age of "ts" people.
# find the name and city who are living in age range of 30 to 60
# find differeNt age group people in "TS"
# find the city name where highest number of people are living


In [ ]:
# ---lec33 completed

In [ ]:
d={"id":[10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200,210,220,230,240,250,260,270,280,290,300,310,320,330],"name":["dhurvi","itty","deepak","dori","lovely","pragati","shayam","sandeep","sangeeta","usha","mahadeo","prem","bablu","harish","harshit","anand","rishita","parwati","jagdish","karan","sanoj","anushkha","daleshwar","kishor","horil","rajesh","chander","badri","parmeshwar","ramu","mahendra","jagdish","ramapati"],"city":["delhi","delhi","mumbai","mumbai","pune","pune","pune","ranchi","kolkatta","pune","orrisa","chennai","haryana","chandigarh","ludhiyana","amritsar","patna","guahati","chennai","kolkatta","orrisa","chennai","haryana","chandigarh","ludhiyana","amritsar","patna","guahati","chennai","kolkatta","delhi","mumbai","banglore"],"designation":["tl","se","se","pm","hr","hr","tl","pm","hr","se","tl","tl","se","se","pm","hr","hr","tl","pm","hr","se","tl","tl","se","se","pm","hr","hr","tl","pm","hr","se","tl"]}

df=pd.DataFrame(d)
print(df)
df.to_csv("D:\\clone\\DataAnalyst_DPK\\files\\workingPeople.csv")

     id        name        city designation
0    10      dhurvi       delhi          tl
1    20        itty       delhi          se
2    30      deepak      mumbai          se
3    40        dori      mumbai          pm
4    50      lovely        pune          hr
5    60     pragati        pune          hr
6    70      shayam        pune          tl
7    80     sandeep      ranchi          pm
8    90    sangeeta    kolkatta          hr
9   100        usha        pune          se
10  110     mahadeo      orrisa          tl
11  120        prem     chennai          tl
12  130       bablu     haryana          se
13  140      harish  chandigarh          se
14  150     harshit   ludhiyana          pm
15  160       anand    amritsar          hr
16  170     rishita       patna          hr
17  180     parwati     guahati          tl
18  190     jagdish     chennai          pm
19  200       karan    kolkatta          hr
20  210       sanoj      orrisa          se
21  220    anushkha     chennai 

In [ ]:
for record in df.iterrows():
    print(record)

(0, id                 10
name           dhurvi
city            delhi
designation        tl
Name: 0, dtype: object)
(1, id                20
name            itty
city           delhi
designation       se
Name: 1, dtype: object)
(2, id                 30
name           deepak
city           mumbai
designation        se
Name: 2, dtype: object)
(3, id                 40
name             dori
city           mumbai
designation        pm
Name: 3, dtype: object)
(4, id                 50
name           lovely
city             pune
designation        hr
Name: 4, dtype: object)
(5, id                  60
name           pragati
city              pune
designation         hr
Name: 5, dtype: object)
(6, id                 70
name           shayam
city             pune
designation        tl
Name: 6, dtype: object)
(7, id                  80
name           sandeep
city            ranchi
designation         pm
Name: 7, dtype: object)
(8, id                   90
name           sangeeta
city           k

In [ ]:
print(df)

     id        name        city designation
0    10      dhurvi       delhi          tl
1    20        itty       delhi          se
2    30      deepak      mumbai          se
3    40        dori      mumbai          pm
4    50      lovely        pune          hr
5    60     pragati        pune          hr
6    70      shayam        pune          tl
7    80     sandeep      ranchi          pm
8    90    sangeeta    kolkatta          hr
9   100        usha        pune          se
10  110     mahadeo      orrisa          tl
11  120        prem     chennai          tl
12  130       bablu     haryana          se
13  140      harish  chandigarh          se
14  150     harshit   ludhiyana          pm
15  160       anand    amritsar          hr
16  170     rishita       patna          hr
17  180     parwati     guahati          tl
18  190     jagdish     chennai          pm
19  200       karan    kolkatta          hr
20  210       sanoj      orrisa          se
21  220    anushkha     chennai 

In [ ]:
# based on index
df.shape

(33, 4)

In [ ]:
print("number of rows=",df.shape[0])

number of rows= 33


In [ ]:
# for columns
for i in range(df.shape[1]):
    print(df.iloc[:,i])
    print("____________________")

0      10
1      20
2      30
3      40
4      50
5      60
6      70
7      80
8      90
9     100
10    110
11    120
12    130
13    140
14    150
15    160
16    170
17    180
18    190
19    200
20    210
21    220
22    230
23    240
24    250
25    260
26    270
27    280
28    290
29    300
30    310
31    320
32    330
Name: id, dtype: int64
____________________
0         dhurvi
1           itty
2         deepak
3           dori
4         lovely
5        pragati
6         shayam
7        sandeep
8       sangeeta
9           usha
10       mahadeo
11          prem
12         bablu
13        harish
14       harshit
15         anand
16       rishita
17       parwati
18       jagdish
19         karan
20         sanoj
21      anushkha
22     daleshwar
23        kishor
24         horil
25        rajesh
26       chander
27         badri
28    parmeshwar
29          ramu
30      mahendra
31       jagdish
32      ramapati
Name: name, dtype: object
____________________
0          delhi
1

In [ ]:
df.columns

Index(['id', 'name', 'city', 'designation'], dtype='object')

In [ ]:
df.columns[::-1]

Index(['designation', 'city', 'name', 'id'], dtype='object')

# iterate the over rows and columns  of dataframe
- 1. iterate over rows of dataframe by index labels
- iterrows()
- 2. iterate over rows of dataframe by index position
- df.shape[0]
- 3. iterate over rows of dataframe by columns names
- df.columns
- 4. iterate over rows of dataframe by columns numbers
- df.shape[1]

In [ ]:
#for (index_label,index_series) in df.iterrows():
 #   print(index_label)
 #   print(index_series)
#    print("____________________")

In [ ]:
# ITERATE OVER SEQUENCE OF COLUMNS

In [ ]:
#df.columns
# df.shape

In [ ]:
# pandas merging dataframe
# dfNew = pd.concat([firstDF,secondDF,thirdDF])
# print(dfNew)
# must have same number of columns

In [ ]:
# transpose dataframe
# transposeData=df.T 

In [ ]:
#lec35