# NumPy, Pandas, Matplotlib

- NumPy
- creation of numpy array
- array()
- arrange()
- linspace()
- zeros()
- Ones()
- full()
- eye()
- identity()
- diag()
- empty()
- random library function

- randint()
- rand()
- uniform()
- randn()
- normal()
- shuffle()
-------------------------

- Array attributes & numpy data types
- view vs copy

------------------

- Indexing, Slicing and advance Indexing
- basic indexing- to select only one element
- slicing - to select multiple arbitrary element
- condition based selection

------------------

- how to iterate element of the nd array

- by python loop
- by numpy nditer() function
- by using ndenumerate() function

------------------

Arithmetics operation:
- arithmetics operation for numpy array with scaler
- arithmetics operation for array with array


----------------------
Array manipulation function

- reshape()
- resize() 
- flatten()
- flat variable
- ravel()
- transpose()
- swapaxes()


--------------
- Joining of multiple array into a single array

- concatenate()
- stack()
- vstack()
- hstack()
- dstack()

--------------
- splitting of array 

- split()
- vsplit()
- hsplit()
- dsplit()

--------------
- how to insert element from ndarray

- insert()
- append()

---------------

- deleting element from ndarray
- matrix multiplication
- importance of matrix class in numpy library.

--------------
- Linear algebra function from linalg module
- inv() - to find the inverse of matrix
- matrix_power() - to find the power of matrix A^n
- det() - to find the determinant of matrix
- solve() - to solve the linear algebra question
-  I/O  operation with numpy 
- basic statistics with numpy
- numpy mathematics function
- how to find unique items and count.


In [1]:
"""
Pre requisite-
 Data type
 loop
 function
 
"""

'\nPre requisite-\n Data type\n loop\n function\n \n'

- Numpy stand for numerical python 
- to deal with arrays based computing + complex operation
- travis oliphan developed numpy 
- he developed numpy in C, Python language.

In [3]:
lst=[[10,20],[30,40]]
print(lst)

[[10, 20], [30, 40]]


In [4]:
for row in lst:
    print(row)

[10, 20]
[30, 40]


In [1]:
""""
- ndarray - mean n dimension array
- pip install numpy

- to uninstall
pip uninstall numpy

# to install and uninstall you need internet connection
because pip is connected to github

-to find the version of numpy
import numpy
print(np.__version__)

"""

'"\n- ndarray - mean n dimension array\n- pip install numpy\n\n- to uninstall\npip uninstall numpy\n\n# to install and uninstall you need internet connection\nbecause pip is connected to github\n\n-to find the version of numpy\nimport numpy\nprint(np.__version__)\n\n'

In [2]:
import numpy as np
print(np.__version__)



2.2.2


In [7]:
lst=[10,20,30,40,50,60,15,10,35,20,30]
a=np.array(lst)
print(a,type(a))

[10 20 30 40 50 60 15 10 35 20 30] <class 'numpy.ndarray'>


In [8]:
a=a+1
print(a,type(a))

[11 21 31 41 51 61 16 11 36 21 31] <class 'numpy.ndarray'>


In [9]:
# how to find the memory size 
import sys
lst1=[10,20,30]
print(sys.getsizeof(lst1))

88


In [1]:
# vector based operation is done with numpy.
# nd array take less memory space for large scale data 
#

# Numpy

"""  
- numpy stand for numerical python .
- numpy is one of the pre define third party module / library and numpy module is not pre define module in python.
- syntax for installing any module in python:
    pip install numpy
    
- to use numpy as a part of our program , we must import numpy module.
- a numpy module is collection of variable, function, and classes.
____________________

History of numpy:-

- developed in 2005 by travis oliphan.
- to solve complex math.
- numpy is developed in c and python language.

- in numpy programming , data is organise in the object of "ndarray". which is one of the pre defined class in numpy.
- hence object of ndarray can store same type or different type ( unique+duplicate ) in single object.

__________________________

# Advantage of numpy.

- with revolution of data science , data analysis like numpy, scipy, scikit and pandas etc., have seen a lot of growth.
- numpy provide a convenient and efficient way to handle the vast amount of data .
- numpy can also do matrix operation and data reshaping.
- numpy is fast which makes it resonable to work with large set of data.


- we can perform 1d,2d ,3d multi dimension array.
- numpy maintain minimal memory for large of data .
-  numpy provide fast in performing operation because it internally its data is available at same address.
- numpy provide many inbuilt function for various complex mathematics operation such as statistical, algebraic, trigonometric, financial and many more.
    
"""

# number of ways to create an object of ndarray:-

 
# i want to create a object of list:-
- lst1=list()
#or
- lst2=[]
#or 
- lst3=list({v1,v2,v3})
#or
lst4=list((v1,v2,v3))


In [4]:
# in numpy we can create an object of ndarray with the following ways:-

#1. array()
#2. arange()
#3. linspace()
#4. zeros()
#5. ones()
#6. full()
#7. identity()
#8. eye()
#9. hstack()
#10. vstack()


#numpy.random 
    #a. randint()
    #b. rand()
    #c. uniform()
    #d. randn()
    #e. normal()
    #f. shuffle()
    

In [5]:
#pip show numpy
#pip list

# 1. array()
- syntax:-
- varname=numpy.array(object,dtype)
- this function is used  for converting traditional python objects into ndarray object



In [7]:
import numpy as np
b=90
a=np.array(b)
print(a,type(a))

90 <class 'numpy.ndarray'>


In [9]:
print(a.ndim)

0


In [10]:
print(a.shape)

()


In [11]:
print(a.size)

1


In [12]:
print(a.dtype)

int64


In [13]:
b=3.4
a=np.array(b)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

3.4 <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type float64


In [14]:
b=3.4+4.5j
a=np.array(b)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

(3.4+4.5j) <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type complex128


In [15]:
b="python"
a=np.array(b)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

python <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type <U6


In [17]:
for val in range(1,11):
    print(val,end="\t")

1	2	3	4	5	6	7	8	9	10	

In [18]:
r=range(10,51,2)
a=np.array(r)
print(a,end="\t")

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]	

In [19]:
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50] <class 'numpy.ndarray'>
dimension 1
shape (21,)
size 21
internal data type int64


In [20]:
a=np.array(range(6),dtype=bool)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[False  True  True  True  True  True] <class 'numpy.ndarray'>
dimension 1
shape (6,)
size 6
internal data type bool


In [21]:
a=np.array(range(6),dtype=int)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[0 1 2 3 4 5] <class 'numpy.ndarray'>
dimension 1
shape (6,)
size 6
internal data type int64


# now i want to reshape the 1D to 2D array:-

- syntax: for shape attribute
- ndarrayobj.shape=(rows,cols)
-  syntax: for reshape attribute
- ndarrayobj=ndarrayobj.reshape(rows,cols)

In [22]:
a=np.array(range(100,156,5))
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
dimension 1
shape (12,)
size 12
internal data type int64


In [23]:
a.shape=(4,3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[100 105 110]
 [115 120 125]
 [130 135 140]
 [145 150 155]] <class 'numpy.ndarray'>
dimension 2
shape (4, 3)
size 12
internal data type int64


In [24]:
a.shape=(12,)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
dimension 1
shape (12,)
size 12
internal data type int64


In [25]:
a.reshape(4,3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
dimension 1
shape (12,)
size 12
internal data type int64


In [26]:
a=a.reshape(12,)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
dimension 1
shape (12,)
size 12
internal data type int64


In [27]:
a=np.array(range(0,16))
a.shape=(2,2,2,2)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]] <class 'numpy.ndarray'>
dimension 4
shape (2, 2, 2, 2)
size 16
internal data type int64


In [28]:
lst=[10,20,30,40,50,60,70,80,90,100,110,120,130,140,160]
a.shape=(4,4)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>
dimension 2
shape (4, 4)
size 16
internal data type int64


In [29]:
a.shape=(2,2,4)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] <class 'numpy.ndarray'>
dimension 3
shape (2, 2, 4)
size 16
internal data type int64


In [30]:
# to flatten
a.shape=(16,)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] <class 'numpy.ndarray'>
dimension 1
shape (16,)
size 16
internal data type int64


In [31]:
s1={10,20,30,40,50,60}
print(s1,type(s1))

{50, 20, 40, 10, 60, 30} <class 'set'>


In [32]:
a=np.array(s1)

print(a,type(a))

{50, 20, 40, 10, 60, 30} <class 'numpy.ndarray'>


In [33]:
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

{50, 20, 40, 10, 60, 30} <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type object


In [34]:
d1={10:"python",20:"java",30:"c",40:"c++"}

a=np.array(d1)
print(a,type(a))
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

{10: 'python', 20: 'java', 30: 'c', 40: 'c++'} <class 'numpy.ndarray'>
{10: 'python', 20: 'java', 30: 'c', 40: 'c++'} <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type object
