# NumPy, Pandas, Matplotlib

- NumPy
- creation of numpy array
- array()
- arange()
- linspace()
- zeros()
- Ones()
- full()
- eye()
- identity()
- diag()
- empty()
- random library function

- randint()
- rand()
- uniform()
- randn()
- normal()
- shuffle()
-------------------------

- Array attributes & numpy data types
- view vs copy

------------------

- Indexing, Slicing and advance Indexing
- basic indexing- to select only one element
- slicing - to select multiple arbitrary element
- condition based selection

------------------

- how to iterate element of the nd array

- by python loop
- by numpy nditer() function
- by using ndenumerate() function

------------------

Arithmetics operation:
- arithmetics operation for numpy array with scaler
- arithmetics operation for array with array


----------------------
Array manipulation function

- reshape()
- resize() 
- flatten()
- flat variable
- ravel()
- transpose()
- swapaxes()


--------------
- Joining of multiple array into a single array

- concatenate()
- stack()
- vstack()
- hstack()
- dstack()

--------------
- splitting of array 

- split()
- vsplit()
- hsplit()
- dsplit()

--------------
- how to insert element from ndarray

- insert()
- append()

---------------

- deleting element from ndarray
- matrix multiplication
- importance of matrix class in numpy library.

--------------
- Linear algebra function from linalg module
- inv() - to find the inverse of matrix
- matrix_power() - to find the power of matrix A^n
- det() - to find the determinant of matrix
- solve() - to solve the linear algebra question
-  I/O  operation with numpy 
- basic statistics with numpy
- numpy mathematics function
- how to find unique items and count.


In [1]:
"""
Pre requisite-
 Data type
 loop
 function
 
"""

'\nPre requisite-\n Data type\n loop\n function\n \n'

- Numpy stand for numerical python 
- to deal with arrays based computing + complex operation
- travis oliphan developed numpy 
- he developed numpy in C, Python language.

In [3]:
lst=[[10,20],[30,40]]
print(lst)

[[10, 20], [30, 40]]


In [4]:
for row in lst:
    print(row)

[10, 20]
[30, 40]


In [1]:
""""
- ndarray - mean n dimension array
- pip install numpy

- to uninstall
pip uninstall numpy

# to install and uninstall you need internet connection
because pip is connected to github

-to find the version of numpy
import numpy
print(np.__version__)

"""

'"\n- ndarray - mean n dimension array\n- pip install numpy\n\n- to uninstall\npip uninstall numpy\n\n# to install and uninstall you need internet connection\nbecause pip is connected to github\n\n-to find the version of numpy\nimport numpy\nprint(np.__version__)\n\n'

In [2]:
import numpy as np
print(np.__version__)



2.2.2


In [7]:
lst=[10,20,30,40,50,60,15,10,35,20,30]
a=np.array(lst)
print(a,type(a))

[10 20 30 40 50 60 15 10 35 20 30] <class 'numpy.ndarray'>


In [8]:
a=a+1
print(a,type(a))

[11 21 31 41 51 61 16 11 36 21 31] <class 'numpy.ndarray'>


In [9]:
# how to find the memory size 
import sys
lst1=[10,20,30]
print(sys.getsizeof(lst1))

88


In [1]:
# vector based operation is done with numpy.
# nd array take less memory space for large scale data 
#

# Numpy

"""  
- numpy stand for numerical python .
- numpy is one of the pre define third party module / library and numpy module is not pre define module in python.
- syntax for installing any module in python:
    pip install numpy
    
- to use numpy as a part of our program , we must import numpy module.
- a numpy module is collection of variable, function, and classes.
____________________

History of numpy:-

- developed in 2005 by travis oliphan.
- to solve complex math.
- numpy is developed in c and python language.

- in numpy programming , data is organise in the object of "ndarray". which is one of the pre defined class in numpy.
- hence object of ndarray can store same type or different type ( unique+duplicate ) in single object.

__________________________

# Advantage of numpy.

- with revolution of data science , data analysis like numpy, scipy, scikit and pandas etc., have seen a lot of growth.
- numpy provide a convenient and efficient way to handle the vast amount of data .
- numpy can also do matrix operation and data reshaping.
- numpy is fast which makes it resonable to work with large set of data.


- we can perform 1d,2d ,3d multi dimension array.
- numpy maintain minimal memory for large of data .
-  numpy provide fast in performing operation because it internally its data is available at same address.
- numpy provide many inbuilt function for various complex mathematics operation such as statistical, algebraic, trigonometric, financial and many more.
    
"""

# number of ways to create an object of ndarray:-

 
# i want to create a object of list:-
- lst1=list()
#or
- lst2=[]
#or 
- lst3=list({v1,v2,v3})
#or
lst4=list((v1,v2,v3))


In [4]:
# in numpy we can create an object of ndarray with the following ways:-

#1. array()
#2. arange()
#3. linspace()
#4. zeros()
#5. ones()
#6. full()
#7. identity()
#8. eye()
#9. hstack()
#10. vstack()


#numpy.random 
    #a. randint()
    #b. rand()
    #c. uniform()
    #d. randn()
    #e. normal()
    #f. shuffle()
    

In [5]:
#pip show numpy
#pip list

# 1. array()
- syntax:-
- varname=numpy.array(object,dtype)
- this function is used  for converting traditional python objects into ndarray object



In [7]:
import numpy as np
b=90
a=np.array(b)
print(a,type(a))

90 <class 'numpy.ndarray'>


In [9]:
print(a.ndim)

0


In [10]:
print(a.shape)

()


In [11]:
print(a.size)

1


In [12]:
print(a.dtype)

int64


In [13]:
b=3.4
a=np.array(b)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

3.4 <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type float64


In [14]:
b=3.4+4.5j
a=np.array(b)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

(3.4+4.5j) <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type complex128


In [15]:
b="python"
a=np.array(b)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

python <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type <U6


In [17]:
for val in range(1,11):
    print(val,end="\t")

1	2	3	4	5	6	7	8	9	10	

In [18]:
r=range(10,51,2)
a=np.array(r)
print(a,end="\t")

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]	

In [19]:
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50] <class 'numpy.ndarray'>
dimension 1
shape (21,)
size 21
internal data type int64


In [20]:
a=np.array(range(6),dtype=bool)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[False  True  True  True  True  True] <class 'numpy.ndarray'>
dimension 1
shape (6,)
size 6
internal data type bool


In [21]:
a=np.array(range(6),dtype=int)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[0 1 2 3 4 5] <class 'numpy.ndarray'>
dimension 1
shape (6,)
size 6
internal data type int64


# now i want to reshape the 1D to 2D array:-

- syntax: for shape attribute
- ndarrayobj.shape=(rows,cols)
-  syntax: for reshape attribute
- ndarrayobj=ndarrayobj.reshape(rows,cols)

In [22]:
a=np.array(range(100,156,5))
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
dimension 1
shape (12,)
size 12
internal data type int64


In [23]:
a.shape=(4,3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[100 105 110]
 [115 120 125]
 [130 135 140]
 [145 150 155]] <class 'numpy.ndarray'>
dimension 2
shape (4, 3)
size 12
internal data type int64


In [24]:
a.shape=(12,)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
dimension 1
shape (12,)
size 12
internal data type int64


In [25]:
a.reshape(4,3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
dimension 1
shape (12,)
size 12
internal data type int64


In [26]:
a=a.reshape(12,)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[100 105 110 115 120 125 130 135 140 145 150 155] <class 'numpy.ndarray'>
dimension 1
shape (12,)
size 12
internal data type int64


In [27]:
a=np.array(range(0,16))
a.shape=(2,2,2,2)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]] <class 'numpy.ndarray'>
dimension 4
shape (2, 2, 2, 2)
size 16
internal data type int64


In [28]:
lst=[10,20,30,40,50,60,70,80,90,100,110,120,130,140,160]
a.shape=(4,4)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>
dimension 2
shape (4, 4)
size 16
internal data type int64


In [29]:
a.shape=(2,2,4)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] <class 'numpy.ndarray'>
dimension 3
shape (2, 2, 4)
size 16
internal data type int64


In [30]:
# to flatten
a.shape=(16,)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] <class 'numpy.ndarray'>
dimension 1
shape (16,)
size 16
internal data type int64


In [31]:
s1={10,20,30,40,50,60}
print(s1,type(s1))

{50, 20, 40, 10, 60, 30} <class 'set'>


In [32]:
a=np.array(s1)

print(a,type(a))

{50, 20, 40, 10, 60, 30} <class 'numpy.ndarray'>


In [33]:
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

{50, 20, 40, 10, 60, 30} <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type object


In [34]:
d1={10:"python",20:"java",30:"c",40:"c++"}

a=np.array(d1)
print(a,type(a))
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

{10: 'python', 20: 'java', 30: 'c', 40: 'c++'} <class 'numpy.ndarray'>
{10: 'python', 20: 'java', 30: 'c', 40: 'c++'} <class 'numpy.ndarray'>
dimension 0
shape ()
size 1
internal data type object


# 2. arange()
- arange() is used for generating range of values with equal interval of value(default interval value or step value is 1)
- syntax:-
- varname=numpy.arange(start)
- varname=numpy.arange(start,end)
- varname=numpy.arange(start,end,step)

- arange() by default create an object of ndarray with 1D  array only ,it cannot built 2D and n-dimension array

- to built 2D and n-D array from arange() function we use reshape() or shape attribute.
 

In [2]:
import numpy as np
a=np.arange(10)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
dimension 1
shape (10,)
size 10
internal data type int64


In [3]:
a.shape=(5,2)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] <class 'numpy.ndarray'>
dimension 2
shape (5, 2)
size 10
internal data type int64


In [4]:
a=np.arange(10,22)
print(a,type(a),len(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[10 11 12 13 14 15 16 17 18 19 20 21] <class 'numpy.ndarray'> 12
dimension 1
shape (12,)
size 12
internal data type int64


In [5]:
a.shape=(2,2,3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]] <class 'numpy.ndarray'>
dimension 3
shape (2, 2, 3)
size 12
internal data type int64


In [6]:
a=np.arange(10,22).reshape(2,3,2)
print(a,type(a))

[[[10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]]] <class 'numpy.ndarray'>


In [7]:
a=np.arange(10,106,5).reshape(5,4)
print(a,type(a),len(a))

[[ 10  15  20  25]
 [ 30  35  40  45]
 [ 50  55  60  65]
 [ 70  75  80  85]
 [ 90  95 100 105]] <class 'numpy.ndarray'> 5


# linspace()
- syntax:-
- varname=numpy.linspace(start,stop,num,endpoint,restep,dtype)
- 

In [8]:
a=np.linspace(1,2)

print(a,type(a))

[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ] <class 'numpy.ndarray'>


In [9]:
a=np.linspace(1,2,num=5)
print(a,type(a))

[1.   1.25 1.5  1.75 2.  ] <class 'numpy.ndarray'>


In [10]:
a=np.linspace(1,2,num=5,endpoint=False)
print(a,type(a))

[1.  1.2 1.4 1.6 1.8] <class 'numpy.ndarray'>


In [11]:
a=np.linspace(1,2,num=5,retstep=True)
print(a,type(a))

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), np.float64(0.25)) <class 'tuple'>


# zeros()
- syntax:-
- varname=numpy.zeros(shape,dtype)

In [13]:
l1=[0,0,0,0]
a=np.array(l1)
print(a,type(a))
a.shape=(2,2)
print(a,type(a))

[0 0 0 0] <class 'numpy.ndarray'>
[[0 0]
 [0 0]] <class 'numpy.ndarray'>


In [14]:
a=np.zeros((2,2),dtype=int)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[[0 0]
 [0 0]] <class 'numpy.ndarray'>
dimension 2
shape (2, 2)
size 4
internal data type int64


In [15]:
a=np.zeros((3,3,3),dtype=int)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]] <class 'numpy.ndarray'>
dimension 3
shape (3, 3, 3)
size 27
internal data type int64


# ones()
- syntax:-
- 

In [16]:
a=np.ones(3,dtype=int)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[1 1 1] <class 'numpy.ndarray'>
dimension 1
shape (3,)
size 3
internal data type int64


In [17]:
a=np.ones((2,3,4),dtype=int)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] <class 'numpy.ndarray'>
dimension 3
shape (2, 3, 4)
size 24
internal data type int64


# full()
- syntax:-
- varname=numpy.full(shape,fill_value,dtype)


In [18]:
a=np.full(6,9)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[9 9 9 9 9 9] <class 'numpy.ndarray'>
dimension 1
shape (6,)
size 6
internal data type int64


In [19]:
a=np.full(6,9).reshape(2,3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[[9 9 9]
 [9 9 9]] <class 'numpy.ndarray'>
dimension 2
shape (2, 3)
size 6
internal data type int64


In [20]:
a=np.full((3,3),6)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)


[[6 6 6]
 [6 6 6]
 [6 6 6]] <class 'numpy.ndarray'>
dimension 2
shape (3, 3)
size 9
internal data type int64


In [21]:
a=np.full((3,3,3),6)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[[6 6 6]
  [6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]]] <class 'numpy.ndarray'>
dimension 3
shape (3, 3, 3)
size 27
internal data type int64


In [22]:
a=np.full((3,3,3),"itty")
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']]

 [['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']]

 [['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']
  ['itty' 'itty' 'itty']]] <class 'numpy.ndarray'>
dimension 3
shape (3, 3, 3)
size 27
internal data type <U4


# identity()
- syntax:-
- varname=numpy.identity(N,dtype)

In [23]:
a=np.identity(3)
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("internal data type",a.dtype)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <class 'numpy.ndarray'>
dimension 2
shape (3, 3)
size 9
internal data type float64


# eye()

- varname= numpy.eye(N,M=none,k=0,dtype)

In [24]:
a= np.identity(5,dtype=int)
print(a,type(a))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] <class 'numpy.ndarray'>


In [25]:
a= np.eye(5,dtype=int)
print(a,type(a))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] <class 'numpy.ndarray'>


In [26]:
a= np.eye(5,k=-1,dtype=int)
print(a,type(a))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]] <class 'numpy.ndarray'>


In [27]:
a= np.eye(5,k=-2,dtype=int)
print(a,type(a))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]] <class 'numpy.ndarray'>


In [28]:
a= np.eye(3,5,dtype=int)
print(a,type(a))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]] <class 'numpy.ndarray'>


In [29]:
a= np.eye(5,3,dtype=int)
print(a,type(a))

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]] <class 'numpy.ndarray'>


# Random number generation in numpy:-
- numpy.random
- 1. randint()
- 2. rand()
- 3. uniform()
- 4. randn()
- 5. normal()
- 6. shuffle()


- --> these are very much useful data science algorithm.(random number generation in numpy:-)

In [30]:
import numpy as np
""" 
_____________________________________  
 1. randint() :- 
 syntax:-
 randint(low, high=None, size=None, dtype=int)
_____________________________________
- 2. rand()
_____________________________________
- 3. uniform()
_____________________________________
- 4. randn()
_____________________________________
- 5. normal()
_____________________________________
- 6. shuffle()
_____________________________________



"""


' \n_____________________________________  \n 1. randint() :- \n syntax:-\n randint(low, high=None, size=None, dtype=int)\n_____________________________________\n- 2. rand()\n_____________________________________\n- 3. uniform()\n_____________________________________\n- 4. randn()\n_____________________________________\n- 5. normal()\n_____________________________________\n- 6. shuffle()\n_____________________________________\n\n\n\n'

In [31]:
a=np.random.randint(10)
print(a,type(a))

0 <class 'int'>


In [32]:
a=np.random.randint(10,30,size=(10,20))
print(a,type(a))

[[12 21 12 26 20 10 26 24 26 19 13 22 19 21 12 26 27 10 13 11]
 [11 14 22 16 21 24 25 29 20 17 21 16 15 25 10 10 20 22 20 28]
 [25 17 24 18 29 28 22 19 19 13 15 24 18 10 27 11 12 25 12 15]
 [21 10 22 21 27 26 21 17 29 26 17 11 29 18 16 26 14 14 14 21]
 [19 14 18 15 26 18 24 25 29 15 10 19 25 19 21 14 17 16 12 18]
 [15 22 10 10 11 24 18 16 28 11 16 12 13 26 15 20 16 27 23 29]
 [26 25 27 25 21 28 13 15 13 21 14 22 22 18 12 16 25 13 18 24]
 [13 28 12 20 22 13 29 17 27 15 15 18 27 25 21 13 26 28 27 22]
 [20 18 20 22 10 18 10 23 26 22 20 16 26 27 11 15 21 23 17 18]
 [11 26 23 24 18 13 24 13 22 17 29 13 18 21 24 18 11 15 14 21]] <class 'numpy.ndarray'>


In [33]:
a=np.random.randint(10,30,size=(3,3,3))
print(a,type(a))

[[[12 12 23]
  [19 24 12]
  [14 12 15]]

 [[12 24 13]
  [14 19 21]
  [19 19 27]]

 [[15 18 29]
  [22 20 28]
  [21 27 14]]] <class 'numpy.ndarray'>


In [34]:
a=np.random.randint(10,30,size=(2,2,2,2))
print(a,type(a))

[[[[26 18]
   [17 19]]

  [[11 26]
   [17 16]]]


 [[[20 20]
   [24 20]]

  [[23 26]
   [12 18]]]] <class 'numpy.ndarray'>


In [35]:
# multi dimension array are used in image processing

In [36]:
a=np.random.randint(10,30,dtype=float)
print(a,type(a))

TypeError: Unsupported dtype dtype('float64') for randint

In [37]:
# rand()---> generating random integer values between 0.0 and 1.0

"""  

"""
# randn()---> generating random integer values between 0.0 and 1.0 (normal distribution)
"""  

"""


'  \n\n'

In [38]:
a=np.random.uniform(1.5,2.9,size=(2,3,3,3))
print(a,type(a))
print("dimension",a.ndim)
print("shape",a.shape)
print("size",a.size)
print("dtype",a.dtype)

[[[[2.08851978 2.66759212 1.86344694]
   [2.22547847 1.59337147 2.28022215]
   [2.42596536 2.73153228 2.71123368]]

  [[1.76871019 2.77794028 2.73464789]
   [2.86490528 1.55705042 2.11778691]
   [2.63163652 2.25165703 1.69511772]]

  [[2.07223973 2.05762932 2.21650431]
   [2.77046553 2.19935115 2.26308615]
   [2.76217697 2.35458837 1.66862355]]]


 [[[2.72158641 2.09978997 2.30443615]
   [2.44682336 1.9924728  1.58111492]
   [2.3334867  2.32077649 2.14452618]]

  [[2.79808995 1.88832343 2.0536822 ]
   [2.45071752 1.8209472  2.31531861]
   [2.46999475 1.88395301 1.95614113]]

  [[1.65071917 2.0504026  1.58282654]
   [2.37617944 2.50885632 1.54609237]
   [2.46516692 2.4730309  2.72038159]]]] <class 'numpy.ndarray'>
dimension 4
shape (2, 3, 3, 3)
size 54
dtype float64


In [2]:
import numpy as np
a=np.random.randint(1,101,size=(5,6))
print(a,type(a))

[[ 90  22  52  36   9  71]
 [ 48  54  96 100  43  59]
 [ 65  26  77  89  21  58]
 [ 32  84  87  81  44  73]
 [ 31  31  56  41   2  76]] <class 'numpy.ndarray'>


In [3]:
np.random.shuffle(a)
print(a)

[[ 31  31  56  41   2  76]
 [ 32  84  87  81  44  73]
 [ 90  22  52  36   9  71]
 [ 48  54  96 100  43  59]
 [ 65  26  77  89  21  58]]


In [4]:
a=np.arange(0,16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [5]:
a=np.arange(0,16).reshape(2,2,2,2)
print(a)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [6]:
help(np.hstack)

Help on _ArrayFunctionDispatcher in module numpy:

hstack(tup, *, dtype=None, casting='same_kind')
    Stack arrays in sequence horizontally (column wise).

    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.

    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.

    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length. In the case of a single
        array_like input, it will be treated as a sequence of arrays; i.e.,
        each element along the zeroth axis is treated as a separate array.

 

In [7]:
a=np.arange(13)
b=np.array_split(a,4)
print(b)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


In [8]:
# 0:4 => 0 to 4-1
# 4:5 => 4 to 5-1


# NumPy index
- indexing is the process of obtaining single value from given iterable object.
- the values of iterable object contain +ve index and -ve index
- object of ndarray is also one of the iterable objects. also contain +ve and -ve index.
- in numpy  programmning , we can apply indexing operation on 3 types of array , they are :-
    - 1-D indexing
    - 2-D indexing
    - N-D indexing
________________________________________

# 1-D indexing
- syntax:-
    - 1darray[index]

    - here inding can be +ve  or -ve
    - if we enter valid index then we get corrosponding value from 1d array
    - if we enter invalid index then we get an IndexError.
    



In [9]:
# example on indexing operation
import numpy as np

In [10]:
a=np.array([10,20,30,40,50,60])
print("1.",a[3])
print("2.",a[-1])
print("3.",a[-6])
print("4.",a[len(a)-1])
print("5.",a[-len(a)])
print("6.",a[100])

1. 40
2. 60
3. 10
4. 60
5. 10


IndexError: index 100 is out of bounds for axis 0 with size 6

In [11]:
print("content of a=",a)
print("Dimension =",a.ndim)
print("shape=",a.shape)
print("size=",a.size)

content of a= [10 20 30 40 50 60]
Dimension = 1
shape= (6,)
size= 6


In [12]:
print("item size  of a=",a.itemsize)

item size  of a= 8


# 2D Indexing
- syntax:-
    - 2darray[row_index][col_index] 
    - or 
    - 2darray[row_index,col_index]

In [13]:
a=np.arange(16).reshape(4,4)
print(a,type(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>


In [14]:
# to get 5
a[1,1]

np.int64(5)

In [15]:
# to get 5
a[1][1]

np.int64(5)

In [16]:
# you can get via -ve indexing
a[-3,-3]

np.int64(5)

In [17]:
# to get 10
a[-2,-2]

np.int64(10)

# 3D indexing
$ or $
# ND indexing

- Syntax:-
    - ndarrayObject[matrixIndex,RowIndex,ColIndex]
    - ndarrayObject[matrixIndex],[rowIndex][colIndex]

In [18]:
a=np.arange(27).reshape(3,3,3)
print(a,type(a))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] <class 'numpy.ndarray'>


In [19]:
print("content of a=",a)
print("Dimension =",a.ndim)
print("shape=",a.shape)
print("size=",a.size)

content of a= [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimension = 3
shape= (3, 3, 3)
size= 27


In [20]:
# to get 4
a[0,1,1]

np.int64(4)

In [21]:
#to get 4
a[-3,-2,-2]

np.int64(4)

In [22]:
#to get 4
a[-3][-2][-2]

np.int64(4)

# Slicing:-
- 1D
- 2D
- 3D OR ND

In [23]:
a= np.array("mississippi")
print("content of a=",a)
print("Dimension =",a.ndim)
print("shape=",a.shape)
print("size=",a.size)

content of a= mississippi
Dimension = 0
shape= ()
size= 1


In [24]:
a= np.array(["mississippi"])
print("content of a=",a)
print("Dimension =",a.ndim)
print("shape=",a.shape)
print("size=",a.size)

content of a= ['mississippi']
Dimension = 1
shape= (1,)
size= 1


In [25]:
a= np.array(list("mississippi"))
print("content of a=",a)
print("Dimension =",a.ndim)
print("shape=",a.shape)
print("size=",a.size)

content of a= ['m' 'i' 's' 's' 'i' 's' 's' 'i' 'p' 'p' 'i']
Dimension = 1
shape= (11,)
size= 11


- the process of obtaining range of values or sub values from an iterable object is called slicing.
- we can apply slicing operations on 3 type of ndarray. they are 
    - 1-D array
    - 2-D array
    - 3-D array /ND array

# 1D array:-
- syntax:- ndarray[begin:end]
    - gives range of values from the begin index to end-1 index provided begin<end
    - syntax:- adarray[begin:]
    - syntax:- adarray[:end]
    - syntax:- adarray[:]
    - syntax:- adarray[begin:end:step]


# syntax for 2D slicing:-
- 2DArrayObj[rowbegin:rowend:rowstep,colbegin:colend,colStep[]]

In [3]:
import numpy as np
a=np.arange(16).reshape(4,4)
print(a,type(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>


In [2]:
a[0:4,0:1]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [3]:
a[:,0:1]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [4]:
a[::,:1]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [5]:
# want 4,5,8,9
a[1:3,0:2]

array([[4, 5],
       [8, 9]])

In [6]:
a[1:4,1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [7]:
a[1:3,0:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
a[1:3,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a[1:3,::]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
# with step value
a[0:4:2,0:4]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [12]:
a[-2:,-2:]

array([[10, 11],
       [14, 15]])

In [13]:
# its not possible t get principle element by using regular indexing and slicing operations
# you can get diagonal element via advance indexing method.
 

In [14]:
a=np.arange(27).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [15]:
"""3D array"""
# [matrixBegin:matrixEnd:matrixStep,rowBegin:rowEnd:rowStep,colBegin:colEnd:colStep]

'3D array'

In [16]:
a[0:2,0:1,0:2]

array([[[ 0,  1]],

       [[ 9, 10]]])

In [17]:
a[:2,:1,:2]

array([[[ 0,  1]],

       [[ 9, 10]]])

In [18]:
a[:,::2,0:1]

array([[[ 0],
        [ 6]],

       [[ 9],
        [15]],

       [[18],
        [24]]])

In [19]:
a[::2,2:3,::2]

array([[[ 6,  8]],

       [[24, 26]]])

In [20]:
# want corner element
a[:,::2,::2]

array([[[ 0,  2],
        [ 6,  8]],

       [[ 9, 11],
        [15, 17]],

       [[18, 20],
        [24, 26]]])

In [21]:
# to convert 3d to 1d
# use ravel and flaten

In [22]:
"""with slicing operation , we cant get random element 
- for getting random element , we must learn advance indexing and slicing.

"""

'with slicing operation , we cant get random element \n- for getting random element , we must learn advance indexing and slicing.\n\n'

# Advance indexing and slicing
- 2D advance indexing:-
identify the row indices of random element
- syntax : rowindices=(row1,row2,row3..row-n)
- identify the column indices of random element
- syntax : columnindices=(col1,col2,col3..col-n)

- pass the row indices and colindices to original

In [5]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
a.shape=(3,3)
print(a,type(a))

[[10 20 30]
 [40 50 60]
 [70 80 90]] <class 'numpy.ndarray'>


In [ ]:
# to get diagonal element (10,50,90)
rowindices=(0,1,2)# step1
colindices=(0,1,2)#step2
# a[rowindices,colindices]

array([10, 50, 90])

In [7]:
#get reverse diagonal element
print(a)
a[(0,1,2),(2,1,0)]

[[10 20 30]
 [40 50 60]
 [70 80 90]]


array([30, 50, 70])

In [8]:
print(a)
a[(0,1,2,2)(1,1,2,0)] # internally process as a[(0,1),(1,1),(2,2),(2,0)]

[[10 20 30]
 [40 50 60]
 [70 80 90]]


<>:2: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
<>:2: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
C:\Users\deepa\AppData\Local\Temp\ipykernel_16452\1474923528.py:2: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
  a[(0,1,2,2)(1,1,2,0)] # internally process as a[(0,1),(1,1),(2,2),(2,0)]


TypeError: 'tuple' object is not callable

# Numpy filtering the data
- 1D,2D,3D or conditional based retrieval from 1D,2D,3D

In [9]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)


[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [10]:
a.shape=(9,)
print(a)

[10 20 30 40 50 60 70 80 90]


In [11]:

""" 
- procedure-1:-
step1:
create a boolean array
_____________________
step2:-
pass boolean to ndarray
__________

"""

' \n- procedure-1:-\nstep1:\ncreate a boolean array\n_____________________\nstep2:-\npass boolean to ndarray\n__________\n\n'

In [12]:
# get the multiple of 3
ba=a%3==0
print(ba,type(ba))

[False False  True False False  True False False  True] <class 'numpy.ndarray'>


In [13]:
# pass the boolean to ndarray object
a[ba]

array([30, 60, 90])

In [14]:
# get the multiple of 4
a[a%4==0]

array([20, 40, 60, 80])

In [15]:
a=np.array([[10,-20,-30],[40,-50,60],[70,-80,-90]])
print(a,type(a))

[[ 10 -20 -30]
 [ 40 -50  60]
 [ 70 -80 -90]] <class 'numpy.ndarray'>


In [16]:
#get all positive value
pa=a[a>0]
print(pa,type(pa))

[10 40 60 70] <class 'numpy.ndarray'>


In [17]:
#get all the negative value
na=a[a<0]
print(na,type(na))

[-20 -30 -50 -80 -90] <class 'numpy.ndarray'>


# numpy copy vs view
- copy()
- view()

In [18]:
a=np.array([10,20,30,40])
print(a,type(a))

[10 20 30 40] <class 'numpy.ndarray'>


In [19]:
b=a.copy()
print("original array = {} and {}".format(a,type(a)))
print("copied array = {} and {}".format(b,type(b)))


original array = [10 20 30 40] and <class 'numpy.ndarray'>
copied array = [10 20 30 40] and <class 'numpy.ndarray'>


In [20]:
a[0]=100
print("original array = {} and {}".format(a,type(a)))
print("copied array = {} and {}".format(b,type(b)))

original array = [100  20  30  40] and <class 'numpy.ndarray'>
copied array = [10 20 30 40] and <class 'numpy.ndarray'>


# view()

In [21]:
b=a.view()
print("original array = {} and {}".format(a,type(a)))
print("copied array = {} and {}".format(b,type(b)))

original array = [100  20  30  40] and <class 'numpy.ndarray'>
copied array = [100  20  30  40] and <class 'numpy.ndarray'>


In [22]:
# it is just deep copy changes on one will affect the others

In [23]:
# arithmetic operation on ndarray
#or
#arithmetic operation
"""   
+
-
*
/
//
%
**

 """

'   \n+\n-\n*\n/\n//\n%\n**\n\n '

In [24]:
import numpy as np
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, device=None, like=None)
    Return a new array of given shape and type, filled with ones.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    device : str, optional
        The device on which to place the created array. Default: None.
        For Array-API interoperability only, so must be ``"cpu"`` if passed.

        .. versionadded:: 2.0.0
    like : array_like, optional
            Reference object to allow the creation of arrays which are not
            NumPy arrays. If an array-like passed in as ``like`` supports
  