In [5]:
import numpy as np
arr1 = np.array([
    [1,2,3],[4,5,6]])
print("Orijinal array :")
print(arr1)
result=np.transpose(arr1)
print("Transpose array:")
print(result)

Orijinal array :
[[1 2 3]
 [4 5 6]]
Transpose array:
[[1 4]
 [2 5]
 [3 6]]
