 ## create an array

In [1]:
import numpy as np
x= np.array([
            [10,20,30],
            [40,50,60],
            [70,80,90]])
print(x)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [2]:
import numpy as np
x= np.array([
            [10,20,30],
            [40,50,60],
            [70,80,90]], dtype=complex )
print(x)

[[10.+0.j 20.+0.j 30.+0.j]
 [40.+0.j 50.+0.j 60.+0.j]
 [70.+0.j 80.+0.j 90.+0.j]]


## how to specifies the binary data

In [3]:
y= np.zeros((2,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
y= np.ones((3,2))
print(y)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
z=np.ones((3,3),dtype=[('m','int'),('n','float')])
print(z)

[[(1, 1.) (1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.) (1, 1.)]]


In [6]:
x= np.array([
            [10,20,30],
            [40,50,60],
            [70,80,90]])
for i in x:
    for j in i:
        print(j,end=" ")  # to print in a new line 
    print() # for print in a new line    


10 20 30 
40 50 60 
70 80 90 


In [7]:
x= np.array([
            [10,20,30],
            [40,50,60],
            [70,80,90]])
print("Row 0:",x[0])
print("Row 1:",x[1])

Row 0: [10 20 30]
Row 1: [40 50 60]


In [8]:
x= np.array([
            [10,20,30],
            [40,50,60],
            [70,80,90]])
print(x[0:2]) # slicing from where to were only aplicable to rows only

[[10 20 30]
 [40 50 60]]


In [9]:
print(x[1:])

[[40 50 60]
 [70 80 90]]


In [10]:
print(x[::-1]) # reversing the rows

[[70 80 90]
 [40 50 60]
 [10 20 30]]


In [11]:
# senario question

In [12]:
print (x[: , 0]) # column wise acess

[10 40 70]


In [13]:
print(x[:0:-1])

[[70 80 90]
 [40 50 60]]


## column representation

In [14]:
print (x[: , 1])# column wise access

[20 50 80]


In [15]:
print("column 0:",x[: ,0])

column 0: [10 40 70]


In [16]:
print("column 2:",x[: ,-1])

column 2: [30 60 90]
